#!/usr/bin/env bash
set -euo pipefail

# UMAP\tSNE\PCA Visualization [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v9.0 (Single run.sh)
# Named argument parsing: --param_name=value format

echo "=== UMAP\tSNE\PCA Visualization [SPAC] [DMAP] ==="

# Copy shared format_values.py from parent directory (if exists)
cp ../format_values.py . 2>/dev/null || true

# Initialize parameters with default values
Color_By="Annotation"
Annotation_to_Highlight="None"
Table="Original"
Feature_to_Highlight="None"
Dimension_Reduction_Method="umap"
Dot_Size=1
Figure_Width=12
Figure_Height=12
Font_Size=12
Figure_DPI=300
Legend_Location="best"
Legend_Font_Size=16
Legend_Marker_Size=5.0
Value_Min="None"
Value_Max="None"

# Print received arguments for debugging
echo "Number of arguments: $#"
echo "Arguments received:"
for arg in "$@"; do
    echo "  $arg"
done

# Parse named arguments dynamically (--param_name=value format)
# Single pattern handles all --key=value arguments
for arg in "$@"; do
    case "$arg" in
        --*=*)
            key="${arg%%=*}"      # everything before '='
            value="${arg#*=}"     # everything after '='
            key="${key#--}"       # remove leading '--'
            export "$key=$value"
            ;;
    esac
done

# Debug: Print parsed parameter values
echo "Color_By: $Color_By"
echo "Annotation_to_Highlight: $Annotation_to_Highlight"
echo "Table: $Table"
echo "Feature_to_Highlight: $Feature_to_Highlight"
echo "Dimension_Reduction_Method: $Dimension_Reduction_Method"
echo "Dot_Size: $Dot_Size"
echo "Figure_Width: $Figure_Width"
echo "Figure_Height: $Figure_Height"
echo "Font_Size: $Font_Size"
echo "Figure_DPI: $Figure_DPI"
echo "Legend_Location: $Legend_Location"
echo "Legend_Font_Size: $Legend_Font_Size"
echo "Legend_Marker_Size: $Legend_Marker_Size"
echo "Value_Min: $Value_Min"
echo "Value_Max: $Value_Max"

# Find input data (pickle/pkl/h5ad)
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No pickle/pkl/h5ad file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Color_By": "$Color_By",
    "Annotation_to_Highlight": "$Annotation_to_Highlight",
    "Table": "$Table",
    "Feature_to_Highlight": "$Feature_to_Highlight",
    "Dimension_Reduction_Method": "$Dimension_Reduction_Method",
    "Dot_Size": $Dot_Size,
    "Figure_Width": $Figure_Width,
    "Figure_Height": $Figure_Height,
    "Font_Size": $Font_Size,
    "Figure_DPI": $Figure_DPI,
    "Legend_Location": "$Legend_Location",
    "Legend_Font_Size": $Legend_Font_Size,
    "Legend_Marker_Size": $Legend_Marker_Size,
    "Value_Min": "$Value_Min",
    "Value_Max": "$Value_Max"
}
EOF

echo '{"figures": {"type": "directory", "name": "figures_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --inject-outputs --outputs-config /results/jsons/outputs_config.json

echo "Normalized: /results/jsons/params.json -> /results/jsons/cleaned_params.json"

# Run SPAC template
python -c "from spac.templates.umap_tsne_pca_visualization_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json', output_dir='/results')"

echo ""
echo "=== Completed. Outputs in /results/ ==="