#!/usr/bin/env bash
set -euo pipefail

# Load CSV Files [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v8.0 (Single run.sh)
# Named argument parsing: --param_name=value format

echo "=== Load CSV Files [SPAC] [DMAP] ==="

# Copy shared format_values.py from parent directory (if exists)
cp ../format_values.py . 2>/dev/null || true

# Initialize parameters with default values
CSV_Files_Pattern="*.csv"
Config_File="*config*.csv"
String_Columns="[]"

# Print received arguments for debugging
echo "Number of arguments: $#"
echo "Arguments received:"
for arg in "$@"; do
    echo "  $arg"
done

# Parse named arguments dynamically (--param_name=value format)
# Based on Conor's example: single pattern handles all --key=value arguments
for arg in "$@"; do
    case "$arg" in
        --*=*)
            key="${arg%%=*}"      # everything before '='
            value="${arg#*=}"     # everything after '='
            key="${key#--}"       # remove leading '--'
            export "$key=$value"
            ;;
    esac
done

# Debug: Print parsed parameter values
echo "CSV_Files_Pattern: $CSV_Files_Pattern"
echo "Config_File: $Config_File"
echo "String_Columns: $String_Columns"

# Find CSV data files (excluding config file)
echo "Searching for CSV files matching pattern: $CSV_Files_Pattern"
CSV_FILES=$(find -L ../data -type f -name "$CSV_Files_Pattern" ! -name "$Config_File" 2>/dev/null | sort)
if [ -z "$CSV_FILES" ]; then echo "ERROR: No CSV data files found in ../data matching pattern: $CSV_Files_Pattern"; exit 1; fi
echo "CSV Files found:"
echo "$CSV_FILES"

# Find configuration file
echo "Searching for config file matching pattern: $Config_File"
CONFIG_INPUT=$(find -L ../data -type f -name "$Config_File" 2>/dev/null | head -n 1)
if [ -z "$CONFIG_INPUT" ]; then echo "ERROR: No configuration file found in ../data matching pattern: $Config_File"; exit 1; fi
echo "Config file: $CONFIG_INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
# Convert CSV_FILES (newline-separated) to JSON array
CSV_FILES_JSON=$(echo "$CSV_FILES" | awk 'BEGIN{printf "["} NR>1{printf ","} {printf "\"%s\"",$0} END{printf "]"}')

cat > /results/jsons/params.json << EOF
{
    "CSV_Files": $CSV_FILES_JSON,
    "CSV_Files_Configuration": "$CONFIG_INPUT",
    "String_Columns": "$String_Columns"
}
EOF

echo '{"dataframe": {"type": "file", "name": "dataframe.csv"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --list-values String_Columns --inject-outputs --outputs-config /results/jsons/outputs_config.json

echo "Normalized: /results/jsons/params.json -> /results/jsons/cleaned_params.json"

# Run SPAC template
python -c "from spac.templates.load_csv_files_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json', output_dir='/results')"

echo ""
echo "=== Completed. Outputs in /results/ ==="