#!/usr/bin/env bash
set -euo pipefail

# Append Pin Color Rule [DMAP] [SPAC]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Append Pin Color Rule [DMAP] [SPAC] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
LABEL_COLOR_MAP="${1:-[]}"
COLOR_MAP_NAME="${2:-_spac_colors}"
OVERWRITE_PREVIOUS_COLOR_MAP="${3:-True}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Label_Color_Map": "$LABEL_COLOR_MAP",
    "Color_Map_Name": "$COLOR_MAP_NAME",
    "Overwrite_Previous_Color_Map": "$OVERWRITE_PREVIOUS_COLOR_MAP"
}
EOF

echo '{"analysis": {"type": "file", "name": "output.pickle"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Overwrite_Previous_Color_Map --list-values Label_Color_Map --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.append_pin_color_rule_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
