#!/usr/bin/env bash
set -euo pipefail

# Normalize Batch [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Normalize Batch [SPAC] [DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
NEED_NORMALIZATION="${1:-False}"
INPUT_TABLE_NAME="${2:-Original}"
OUTPUT_TABLE_NAME="${3:-batch_normalized_table}"
ANNOTATION="${4:-}"
NORMALIZATION_METHOD="${5:-median}"
TAKE_LOG="${6:-False}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Need_Normalization": "$NEED_NORMALIZATION",
    "Input_Table_Name": "$INPUT_TABLE_NAME",
    "Output_Table_Name": "$OUTPUT_TABLE_NAME",
    "Annotation": "$ANNOTATION",
    "Normalization_Method": "$NORMALIZATION_METHOD",
    "Take_Log": "$TAKE_LOG"
}
EOF

echo '{"analysis": {"type": "file", "name": "output.pickle"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Need_Normalization Take_Log --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.normalize_batch_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
