#!/usr/bin/env bash
set -euo pipefail

# Hierarchical Heatmap [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Hierarchical Heatmap [SPAC] [DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
ANNOTATION="${1:-}"
TABLE_TO_VISUALIZE="${2:-Original}"
FEATURE_DENDROGRAM="${3:-True}"
ANNOTATION_DENDROGRAM="${4:-True}"
Z_SCORE="${5:-None}"
SWAP_AXES="${6:-False}"
FEATURE_S_="${7:-["All"]}"
ROTATE_LABEL_="${8:-False}"
FIGURE_TITLE="${9:-Hierarchical Heatmap}"
FIGURE_WIDTH="${10:-8}"
FIGURE_HEIGHT="${11:-8}"
FIGURE_DPI="${12:-300}"
FONT_SIZE="${13:-10}"
MATRIX_PLOT_RATIO="${14:-0.8}"
STANDARD_SCALE_="${15:-None}"
HORIZONTAL_DENDROGRAM_DISPLAY_RATIO="${16:-0.2}"
VERTICAL_DENDROGRAM_DISPLAY_RATIO="${17:-0.2}"
VALUE_MIN="${18:-None}"
VALUE_MAX="${19:-None}"
COLOR_MAP="${20:-seismic}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Annotation": "$ANNOTATION",
    "Table_to_Visualize": "$TABLE_TO_VISUALIZE",
    "Feature_Dendrogram": "$FEATURE_DENDROGRAM",
    "Annotation_Dendrogram": "$ANNOTATION_DENDROGRAM",
    "Z_Score": "$Z_SCORE",
    "Swap_Axes": "$SWAP_AXES",
    "Feature_s_": "$FEATURE_S_",
    "Rotate_Label_": "$ROTATE_LABEL_",
    "Figure_Title": "$FIGURE_TITLE",
    "Figure_Width": "$FIGURE_WIDTH",
    "Figure_Height": "$FIGURE_HEIGHT",
    "Figure_DPI": "$FIGURE_DPI",
    "Font_Size": "$FONT_SIZE",
    "Matrix_Plot_Ratio": "$MATRIX_PLOT_RATIO",
    "Standard_Scale_": "$STANDARD_SCALE_",
    "Horizontal_Dendrogram_Display_Ratio": "$HORIZONTAL_DENDROGRAM_DISPLAY_RATIO",
    "Vertical_Dendrogram_Display_Ratio": "$VERTICAL_DENDROGRAM_DISPLAY_RATIO",
    "Value_Min": "$VALUE_MIN",
    "Value_Max": "$VALUE_MAX",
    "Color_Map": "$COLOR_MAP"
}
EOF

echo '{"dataframe": {"type": "file", "name": "dataframe.csv"}, "figures": {"type": "directory", "name": "figures_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Feature_Dendrogram Annotation_Dendrogram Swap_Axes Rotate_Label_ --list-values Feature_s_ --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.hierarchical_heatmap_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
