#!/usr/bin/env bash
set -euo pipefail

# Hierarchical Heatmap [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v8.0 (Single run.sh)
# Named argument parsing: --param_name=value format

echo "=== Hierarchical Heatmap [SPAC] [DMAP] ==="

# Copy shared format_values.py from parent directory (if exists)
cp ../format_values.py . 2>/dev/null || true

# Initialize parameters with default values
Annotation=""
Table_to_Visualize="Original"
Feature_Dendrogram="True"
Annotation_Dendrogram="True"
Z_Score="None"
Swap_Axes="False"
Feature_s_="["All"]"
Rotate_Label_="False"
Figure_Title="Hierarchical Heatmap"
Figure_Width=8
Figure_Height=8
Figure_DPI=300
Font_Size=10
Matrix_Plot_Ratio=0.8
Standard_Scale_="None"
Horizontal_Dendrogram_Display_Ratio=0.2
Vertical_Dendrogram_Display_Ratio=0.2
Value_Min="None"
Value_Max="None"
Color_Map="seismic"

# Print received arguments for debugging
echo "Number of arguments: $#"
echo "Arguments received:"
for arg in "$@"; do
    echo "  $arg"
done

# Parse named arguments dynamically (--param_name=value format)
# Based on Conor's example: single pattern handles all --key=value arguments
for arg in "$@"; do
    case "$arg" in
        --*=*)
            key="${arg%%=*}"      # everything before '='
            value="${arg#*=}"     # everything after '='
            key="${key#--}"       # remove leading '--'
            export "$key=$value"
            ;;
    esac
done

# Debug: Print parsed parameter values
echo "Annotation: $Annotation"
echo "Table_to_Visualize: $Table_to_Visualize"
echo "Feature_Dendrogram: $Feature_Dendrogram"
echo "Annotation_Dendrogram: $Annotation_Dendrogram"
echo "Z_Score: $Z_Score"
echo "Swap_Axes: $Swap_Axes"
echo "Feature_s_: $Feature_s_"
echo "Rotate_Label_: $Rotate_Label_"
echo "Figure_Title: $Figure_Title"
echo "Figure_Width: $Figure_Width"
echo "Figure_Height: $Figure_Height"
echo "Figure_DPI: $Figure_DPI"
echo "Font_Size: $Font_Size"
echo "Matrix_Plot_Ratio: $Matrix_Plot_Ratio"
echo "Standard_Scale_: $Standard_Scale_"
echo "Horizontal_Dendrogram_Display_Ratio: $Horizontal_Dendrogram_Display_Ratio"
echo "Vertical_Dendrogram_Display_Ratio: $Vertical_Dendrogram_Display_Ratio"
echo "Value_Min: $Value_Min"
echo "Value_Max: $Value_Max"
echo "Color_Map: $Color_Map"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Annotation": "$Annotation",
    "Table_to_Visualize": "$Table_to_Visualize",
    "Feature_Dendrogram": "$Feature_Dendrogram",
    "Annotation_Dendrogram": "$Annotation_Dendrogram",
    "Z_Score": "$Z_Score",
    "Swap_Axes": "$Swap_Axes",
    "Feature_s_": "$Feature_s_",
    "Rotate_Label_": "$Rotate_Label_",
    "Figure_Title": "$Figure_Title",
    "Figure_Width": $Figure_Width,
    "Figure_Height": $Figure_Height,
    "Figure_DPI": $Figure_DPI,
    "Font_Size": $Font_Size,
    "Matrix_Plot_Ratio": $Matrix_Plot_Ratio,
    "Standard_Scale_": "$Standard_Scale_",
    "Horizontal_Dendrogram_Display_Ratio": $Horizontal_Dendrogram_Display_Ratio,
    "Vertical_Dendrogram_Display_Ratio": $Vertical_Dendrogram_Display_Ratio,
    "Value_Min": "$Value_Min",
    "Value_Max": "$Value_Max",
    "Color_Map": "$Color_Map"
}
EOF

echo '{"dataframe": {"type": "file", "name": "dataframe.csv"}, "figures": {"type": "directory", "name": "figures_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Feature_Dendrogram Annotation_Dendrogram Swap_Axes Rotate_Label_ --list-values Feature_s_ --inject-outputs --outputs-config /results/jsons/outputs_config.json

echo "Normalized: /results/jsons/params.json -> /results/jsons/cleaned_params.json"

# Run SPAC template
python -c "from spac.templates.hierarchical_heatmap_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json', output_dir='/results')"

echo ""
echo "=== Completed. Outputs in /results/ ==="