#!/usr/bin/env bash
set -euo pipefail

# Analysis to CSV [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Analysis to CSV [SPAC] [DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
TABLE_TO_EXPORT="${1:-Original}"
SAVE_AS_CSV_FILE="${2:-False}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Table_to_Export": "$TABLE_TO_EXPORT",
    "Save_as_CSV_File": "$SAVE_AS_CSV_FILE"
}
EOF

echo '{"dataframe": {"type": "file", "name": "dataframe.csv"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Save_as_CSV_File --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.analysis_to_csv_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
