#!/usr/bin/env bash
set -euo pipefail

# Visualize Ripley L [SPAC][DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Visualize Ripley L [SPAC][DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
CENTER_PHENOTYPE="${1:-}"
NEIGHBOR_PHENOTYPE="${2:-}"
PLOT_SPECIFIC_REGIONS="${3:-False}"
REGIONS_LABEL_S_="${4:-}"
PLOT_SIMULATIONS="${5:-True}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Center_Phenotype": "$CENTER_PHENOTYPE",
    "Neighbor_Phenotype": "$NEIGHBOR_PHENOTYPE",
    "Plot_Specific_Regions": "$PLOT_SPECIFIC_REGIONS",
    "Regions_Label_s_": "$REGIONS_LABEL_S_",
    "Plot_Simulations": "$PLOT_SIMULATIONS"
}
EOF

echo '{"dataframe": {"type": "file", "name": "dataframe.csv"}, "figures": {"type": "directory", "name": "figures_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Plot_Specific_Regions Plot_Simulations --list-values Regions_Label_s_ --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.visualize_ripley_l_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
