#!/usr/bin/env bash
set -euo pipefail

# Visualize Ripley L [SPAC][DMAP]
# Generated by code_ocean_synthesizer.py v9.0 (Single run.sh)
# Named argument parsing: --param_name=value format

echo "=== Visualize Ripley L [SPAC][DMAP] ==="

# Copy shared format_values.py from parent directory (if exists)
cp ../format_values.py . 2>/dev/null || true

# Initialize parameters with default values
Center_Phenotype=""
Neighbor_Phenotype=""
Plot_Specific_Regions="False"
Regions_Label_s_=""
Plot_Simulations="True"

# Print received arguments for debugging
echo "Number of arguments: $#"
echo "Arguments received:"
for arg in "$@"; do
    echo "  $arg"
done

# Parse named arguments dynamically (--param_name=value format)
# Single pattern handles all --key=value arguments
for arg in "$@"; do
    case "$arg" in
        --*=*)
            key="${arg%%=*}"      # everything before '='
            value="${arg#*=}"     # everything after '='
            key="${key#--}"       # remove leading '--'
            export "$key=$value"
            ;;
    esac
done

# Debug: Print parsed parameter values
echo "Center_Phenotype: $Center_Phenotype"
echo "Neighbor_Phenotype: $Neighbor_Phenotype"
echo "Plot_Specific_Regions: $Plot_Specific_Regions"
echo "Regions_Label_s_: $Regions_Label_s_"
echo "Plot_Simulations: $Plot_Simulations"

# Find input data (pickle/pkl/h5ad)
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No pickle/pkl/h5ad file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Center_Phenotype": "$Center_Phenotype",
    "Neighbor_Phenotype": "$Neighbor_Phenotype",
    "Plot_Specific_Regions": "$Plot_Specific_Regions",
    "Regions_Label_s_": "$Regions_Label_s_",
    "Plot_Simulations": "$Plot_Simulations"
}
EOF

echo '{"dataframe": {"type": "file", "name": "dataframe.csv"}, "figures": {"type": "directory", "name": "figures_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Plot_Specific_Regions Plot_Simulations --list-values Regions_Label_s_ --inject-outputs --outputs-config /results/jsons/outputs_config.json

echo "Normalized: /results/jsons/params.json -> /results/jsons/cleaned_params.json"

# Run SPAC template
python -c "from spac.templates.visualize_ripley_l_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json', output_dir='/results')"

echo ""
echo "=== Completed. Outputs in /results/ ==="