#!/usr/bin/env bash
set -euo pipefail

# Relational Heatmap [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Relational Heatmap [SPAC] [DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
SOURCE_ANNOTATION_NAME="${1:-None}"
TARGET_ANNOTATION_NAME="${2:-None}"
COLORMAP="${3:-darkmint}"
FIGURE_WIDTH_INCH="${4:-8}"
FIGURE_HEIGHT_INCH="${5:-10}"
FIGURE_DPI="${6:-300}"
FONT_SIZE="${7:-8}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Source_Annotation_Name": "$SOURCE_ANNOTATION_NAME",
    "Target_Annotation_Name": "$TARGET_ANNOTATION_NAME",
    "Colormap": "$COLORMAP",
    "Figure_Width_inch": "$FIGURE_WIDTH_INCH",
    "Figure_Height_inch": "$FIGURE_HEIGHT_INCH",
    "Figure_DPI": "$FIGURE_DPI",
    "Font_Size": "$FONT_SIZE"
}
EOF

echo '{"figures": {"type": "directory", "name": "figures_dir"}, "html": {"type": "directory", "name": "html_dir"}, "dataframe": {"type": "file", "name": "dataframe.csv"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.relational_heatmap_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
