#!/usr/bin/env bash
set -euo pipefail

# Z-Score Normalization [DMAP] [SPAC]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Z-Score Normalization [DMAP] [SPAC] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
TABLE_TO_PROCESS="${1:-Original}"
OUTPUT_TABLE_NAME="${2:-z_scores}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Table_to_Process": "$TABLE_TO_PROCESS",
    "Output_Table_Name": "$OUTPUT_TABLE_NAME"
}
EOF

echo '{"analysis": {"type": "file", "name": "output.pickle"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.z_score_normalization_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
