#!/usr/bin/env bash
set -euo pipefail

# UTAG Clustering [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== UTAG Clustering [SPAC] [DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
TABLE_TO_PROCESS="${1:-Original}"
FEATURES="${2:-All}"
SLIDE_ANNOTATION="${3:-None}"
PCA_COMPONENTS="${4:-None}"
K_NEAREST_NEIGHBORS="${5:-15}"
RESOLUTION_PARAMETER="${6:-1}"
DISTANCE_THRESHOLD="${7:-20.0}"
RANDOM_SEED="${8:-42}"
LEIDEN_ITERATIONS="${9:-5}"
OUTPUT_ANNOTATION_NAME="${10:-UTAG}"
PARELLEL_PROCESSES="${11:-False}"
N_JOBS="${12:-1}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Table_to_Process": "$TABLE_TO_PROCESS",
    "Features": "$FEATURES",
    "Slide_Annotation": "$SLIDE_ANNOTATION",
    "PCA_Components": "$PCA_COMPONENTS",
    "K_Nearest_Neighbors": "$K_NEAREST_NEIGHBORS",
    "Resolution_Parameter": "$RESOLUTION_PARAMETER",
    "Distance_Threshold": "$DISTANCE_THRESHOLD",
    "Random_Seed": "$RANDOM_SEED",
    "Leiden_Iterations": "$LEIDEN_ITERATIONS",
    "Output_Annotation_Name": "$OUTPUT_ANNOTATION_NAME",
    "Parellel_Processes": "$PARELLEL_PROCESSES",
    "N_Jobs": "$N_JOBS"
}
EOF

echo '{"analysis": {"type": "file", "name": "output.pickle"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Parellel_Processes --list-values Features --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.utag_clustering_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
