#!/usr/bin/env bash
set -euo pipefail

# UTAG Clustering [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v8.0 (Single run.sh)
# Named argument parsing: --param_name=value format

echo "=== UTAG Clustering [SPAC] [DMAP] ==="

# Copy shared format_values.py from parent directory (if exists)
cp ../format_values.py . 2>/dev/null || true

# Initialize parameters with default values
Table_to_Process="Original"
Features="All"
Slide_Annotation="None"
PCA_Components="None"
K_Nearest_Neighbors=15
Resolution_Parameter=1
Distance_Threshold=20.0
Random_Seed=42
Leiden_Iterations=5
Output_Annotation_Name="UTAG"
Parellel_Processes="False"
N_Jobs=1

# Print received arguments for debugging
echo "Number of arguments: $#"
echo "Arguments received:"
for arg in "$@"; do
    echo "  $arg"
done

# Parse named arguments dynamically (--param_name=value format)
# Based on Conor's example: single pattern handles all --key=value arguments
for arg in "$@"; do
    case "$arg" in
        --*=*)
            key="${arg%%=*}"      # everything before '='
            value="${arg#*=}"     # everything after '='
            key="${key#--}"       # remove leading '--'
            export "$key=$value"
            ;;
    esac
done

# Debug: Print parsed parameter values
echo "Table_to_Process: $Table_to_Process"
echo "Features: $Features"
echo "Slide_Annotation: $Slide_Annotation"
echo "PCA_Components: $PCA_Components"
echo "K_Nearest_Neighbors: $K_Nearest_Neighbors"
echo "Resolution_Parameter: $Resolution_Parameter"
echo "Distance_Threshold: $Distance_Threshold"
echo "Random_Seed: $Random_Seed"
echo "Leiden_Iterations: $Leiden_Iterations"
echo "Output_Annotation_Name: $Output_Annotation_Name"
echo "Parellel_Processes: $Parellel_Processes"
echo "N_Jobs: $N_Jobs"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Table_to_Process": "$Table_to_Process",
    "Features": "$Features",
    "Slide_Annotation": "$Slide_Annotation",
    "PCA_Components": "$PCA_Components",
    "K_Nearest_Neighbors": $K_Nearest_Neighbors,
    "Resolution_Parameter": $Resolution_Parameter,
    "Distance_Threshold": $Distance_Threshold,
    "Random_Seed": $Random_Seed,
    "Leiden_Iterations": $Leiden_Iterations,
    "Output_Annotation_Name": "$Output_Annotation_Name",
    "Parellel_Processes": "$Parellel_Processes",
    "N_Jobs": $N_Jobs
}
EOF

echo '{"analysis": {"type": "file", "name": "output.pickle"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Parellel_Processes --list-values Features --inject-outputs --outputs-config /results/jsons/outputs_config.json

echo "Normalized: /results/jsons/params.json -> /results/jsons/cleaned_params.json"

# Run SPAC template
python -c "from spac.templates.utag_clustering_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json', output_dir='/results')"

echo ""
echo "=== Completed. Outputs in /results/ ==="