#!/usr/bin/env bash
set -euo pipefail

# Combine Annotations [SPAC][DMAP]
# Generated by code_ocean_synthesizer.py v9.0 (Single run.sh)
# Named argument parsing: --param_name=value format

echo "=== Combine Annotations [SPAC][DMAP] ==="

# Copy shared format_values.py from parent directory (if exists)
cp ../format_values.py . 2>/dev/null || true

# Initialize parameters with default values
Annotations_Names=""
New_Annotation_Name="combined_annotation"
Separator="_"

# Print received arguments for debugging
echo "Number of arguments: $#"
echo "Arguments received:"
for arg in "$@"; do
    echo "  $arg"
done

# Parse named arguments dynamically (--param_name=value format)
# Single pattern handles all --key=value arguments
for arg in "$@"; do
    case "$arg" in
        --*=*)
            key="${arg%%=*}"      # everything before '='
            value="${arg#*=}"     # everything after '='
            key="${key#--}"       # remove leading '--'
            export "$key=$value"
            ;;
    esac
done

# Debug: Print parsed parameter values
echo "Annotations_Names: $Annotations_Names"
echo "New_Annotation_Name: $New_Annotation_Name"
echo "Separator: $Separator"

# Find input data (pickle/pkl/h5ad)
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No pickle/pkl/h5ad file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Annotations_Names": "$Annotations_Names",
    "New_Annotation_Name": "$New_Annotation_Name",
    "Separator": "$Separator"
}
EOF

echo '{"dataframe": {"type": "file", "name": "dataframe.csv"}, "analysis": {"type": "file", "name": "output.pickle"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --list-values Annotations_Names --inject-outputs --outputs-config /results/jsons/outputs_config.json

echo "Normalized: /results/jsons/params.json -> /results/jsons/cleaned_params.json"

# Run SPAC template
python -c "from spac.templates.combine_annotations_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json', output_dir='/results')"

echo ""
echo "=== Completed. Outputs in /results/ ==="