#!/usr/bin/env bash
set -euo pipefail

# Phenograph Clustering [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Phenograph Clustering [SPAC] [DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
RUN_ON_HPC="${1:-False}"
TABLE_TO_PROCESS="${2:-Original}"
K_NEAREST_NEIGHBORS="${3:-30}"
SEED="${4:-42}"
RESOLUTION_PARAMETER="${5:-1}"
OUTPUT_ANNOTATION_NAME="${6:-phenograph}"
NUMBER_OF_ITERATIONS="${7:-100}"
PROFILING="${8:-False}"
RESOLUTION_LIST="${9:-[]}"
HPC_COMPUTE_MODE="${10:-CPU}"
BATCH_MODE="${11:-False}"
PARTITION="${12:-quick}"
NUMBER_OF_CPUS="${13:-2}"
MEMORY_GB="${14:-10}"
REQUEST_TIME="${15:-00:20:00}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Run_on_HPC": "$RUN_ON_HPC",
    "Table_to_Process": "$TABLE_TO_PROCESS",
    "K_Nearest_Neighbors": "$K_NEAREST_NEIGHBORS",
    "Seed": "$SEED",
    "Resolution_Parameter": "$RESOLUTION_PARAMETER",
    "Output_Annotation_Name": "$OUTPUT_ANNOTATION_NAME",
    "Number_of_Iterations": "$NUMBER_OF_ITERATIONS",
    "Profiling": "$PROFILING",
    "Resolution_List": "$RESOLUTION_LIST",
    "HPC_Compute_Mode": "$HPC_COMPUTE_MODE",
    "Batch_Mode": "$BATCH_MODE",
    "Partition": "$PARTITION",
    "Number_of_CPUs": "$NUMBER_OF_CPUS",
    "Memory_GB": "$MEMORY_GB",
    "Request_Time": "$REQUEST_TIME"
}
EOF

echo '{"analysis": {"type": "file", "name": "output.pickle"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Run_on_HPC Profiling Batch_Mode --list-values Resolution_List --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.phenograph_clustering_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
