#!/usr/bin/env bash
set -euo pipefail

# Phenograph Clustering [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v8.0 (Single run.sh)
# Named argument parsing: --param_name=value format

echo "=== Phenograph Clustering [SPAC] [DMAP] ==="

# Copy shared format_values.py from parent directory (if exists)
cp ../format_values.py . 2>/dev/null || true

# Initialize parameters with default values
Run_on_HPC="False"
Table_to_Process="Original"
K_Nearest_Neighbors=30
Seed=42
Resolution_Parameter=1
Output_Annotation_Name="phenograph"
Number_of_Iterations=100
Profiling="False"
Resolution_List="[]"
HPC_Compute_Mode="CPU"
Batch_Mode="False"
Partition="quick"
Number_of_CPUs=2
Memory_GB=10
Request_Time="00:20:00"

# Print received arguments for debugging
echo "Number of arguments: $#"
echo "Arguments received:"
for arg in "$@"; do
    echo "  $arg"
done

# Parse named arguments dynamically (--param_name=value format)
# Based on Conor's example: single pattern handles all --key=value arguments
for arg in "$@"; do
    case "$arg" in
        --*=*)
            key="${arg%%=*}"      # everything before '='
            value="${arg#*=}"     # everything after '='
            key="${key#--}"       # remove leading '--'
            export "$key=$value"
            ;;
    esac
done

# Debug: Print parsed parameter values
echo "Run_on_HPC: $Run_on_HPC"
echo "Table_to_Process: $Table_to_Process"
echo "K_Nearest_Neighbors: $K_Nearest_Neighbors"
echo "Seed: $Seed"
echo "Resolution_Parameter: $Resolution_Parameter"
echo "Output_Annotation_Name: $Output_Annotation_Name"
echo "Number_of_Iterations: $Number_of_Iterations"
echo "Profiling: $Profiling"
echo "Resolution_List: $Resolution_List"
echo "HPC_Compute_Mode: $HPC_Compute_Mode"
echo "Batch_Mode: $Batch_Mode"
echo "Partition: $Partition"
echo "Number_of_CPUs: $Number_of_CPUs"
echo "Memory_GB: $Memory_GB"
echo "Request_Time: $Request_Time"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Run_on_HPC": "$Run_on_HPC",
    "Table_to_Process": "$Table_to_Process",
    "K_Nearest_Neighbors": $K_Nearest_Neighbors,
    "Seed": $Seed,
    "Resolution_Parameter": $Resolution_Parameter,
    "Output_Annotation_Name": "$Output_Annotation_Name",
    "Number_of_Iterations": $Number_of_Iterations,
    "Profiling": "$Profiling",
    "Resolution_List": "$Resolution_List",
    "HPC_Compute_Mode": "$HPC_Compute_Mode",
    "Batch_Mode": "$Batch_Mode",
    "Partition": "$Partition",
    "Number_of_CPUs": $Number_of_CPUs,
    "Memory_GB": $Memory_GB,
    "Request_Time": "$Request_Time"
}
EOF

echo '{"analysis": {"type": "file", "name": "output.pickle"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Run_on_HPC Profiling Batch_Mode --list-values Resolution_List --inject-outputs --outputs-config /results/jsons/outputs_config.json

echo "Normalized: /results/jsons/params.json -> /results/jsons/cleaned_params.json"

# Run SPAC template
python -c "from spac.templates.phenograph_clustering_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json', output_dir='/results')"

echo ""
echo "=== Completed. Outputs in /results/ ==="