#!/usr/bin/env bash
set -euo pipefail

# Combine DataFrames [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v9.0 (Single run.sh)
# Named argument parsing: --param_name=value format

echo "=== Combine DataFrames [SPAC] [DMAP] ==="

# Copy shared format_values.py from parent directory (if exists)
cp ../format_values.py . 2>/dev/null || true

# Initialize parameters with default values
First_Dataframe_Pattern="*"
Second_Dataframe_Pattern="*input2*"

# Print received arguments for debugging
echo "Number of arguments: $#"
echo "Arguments received:"
for arg in "$@"; do
    echo "  $arg"
done

# Parse named arguments dynamically (--param_name=value format)
# Single pattern handles all --key=value arguments
for arg in "$@"; do
    case "$arg" in
        --*=*)
            key="${arg%%=*}"      # everything before '='
            value="${arg#*=}"     # everything after '='
            key="${key#--}"       # remove leading '--'
            export "$key=$value"
            ;;
    esac
done

# Debug: Print parsed parameter values
echo "First_Dataframe_Pattern: $First_Dataframe_Pattern"
echo "Second_Dataframe_Pattern: $Second_Dataframe_Pattern"

# Find First Dataframe (CSV/TSV)
echo "Searching for First Dataframe matching pattern: $First_Dataframe_Pattern"
INPUT_1=$(find -L ../data -type f \( -name "$First_Dataframe_Pattern.csv" -o -name "$First_Dataframe_Pattern.tsv" \) 2>/dev/null | head -n 1)
# Fallback: try pattern as-is
if [ -z "$INPUT_1" ]; then INPUT_1=$(find -L ../data -type f -name "$First_Dataframe_Pattern" 2>/dev/null | head -n 1); fi
if [ -z "$INPUT_1" ]; then echo "ERROR: No First Dataframe found matching pattern: $First_Dataframe_Pattern"; exit 1; fi
echo "First Dataframe: $INPUT_1"

# Find Second Dataframe (CSV/TSV)
echo "Searching for Second Dataframe matching pattern: $Second_Dataframe_Pattern"
INPUT_2=$(find -L ../data -type f \( -name "$Second_Dataframe_Pattern.csv" -o -name "$Second_Dataframe_Pattern.tsv" \) 2>/dev/null | head -n 1)
# Fallback: try pattern as-is
if [ -z "$INPUT_2" ]; then INPUT_2=$(find -L ../data -type f -name "$Second_Dataframe_Pattern" 2>/dev/null | head -n 1); fi
if [ -z "$INPUT_2" ]; then echo "ERROR: No Second Dataframe found matching pattern: $Second_Dataframe_Pattern"; exit 1; fi
echo "Second Dataframe: $INPUT_2"


# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "First_Dataframe": "$INPUT_1",
    "Second_Dataframe": "$INPUT_2"
}
EOF

echo '{"dataframe": {"type": "file", "name": "dataframe.csv"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --inject-outputs --outputs-config /results/jsons/outputs_config.json

echo "Normalized: /results/jsons/params.json -> /results/jsons/cleaned_params.json"

# Run SPAC template
python -c "from spac.templates.combine_dataframes_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json', output_dir='/results')"

echo ""
echo "=== Completed. Outputs in /results/ ==="