#!/usr/bin/env bash
set -euo pipefail

# Interactive Spatial Plot [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Interactive Spatial Plot [SPAC] [DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
STRATIFY_BY="${1:-None}"
COLOR_BY="${2:-Annotation}"
ANNOTATION_S_TO_HIGHLIGHT="${3:-[""]}"
FEATURE_TO_HIGHLIGHT="${4:-None}"
TABLE="${5:-Original}"
FONT_SIZE="${6:-12}"
DOT_SIZE="${7:-1.5}"
DOT_TRANSPARENCY="${8:-0.75}"
FLIP_VERTICAL_AXIS="${9:-False}"
FIGURE_WIDTH="${10:-6}"
FIGURE_HEIGHT="${11:-4}"
DEFINE_LABEL_COLOR_MAPPING="${12:-None}"
FIGURE_DPI="${13:-200}"
FEATURE_COLOR_SCALE="${14:-balance}"
LOWER_COLORBAR_BOUND="${15:-999}"
UPPER_COLORBAR_BOUND="${16:--999}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Stratify_By": "$STRATIFY_BY",
    "Color_By": "$COLOR_BY",
    "Annotation_s_to_Highlight": "$ANNOTATION_S_TO_HIGHLIGHT",
    "Feature_to_Highlight": "$FEATURE_TO_HIGHLIGHT",
    "Table": "$TABLE",
    "Font_Size": "$FONT_SIZE",
    "Dot_Size": "$DOT_SIZE",
    "Dot_Transparency": "$DOT_TRANSPARENCY",
    "Flip_Vertical_Axis": "$FLIP_VERTICAL_AXIS",
    "Figure_Width": "$FIGURE_WIDTH",
    "Figure_Height": "$FIGURE_HEIGHT",
    "Define_Label_Color_Mapping": "$DEFINE_LABEL_COLOR_MAPPING",
    "Figure_DPI": "$FIGURE_DPI",
    "Feature_Color_Scale": "$FEATURE_COLOR_SCALE",
    "Lower_Colorbar_Bound": "$LOWER_COLORBAR_BOUND",
    "Upper_Colorbar_Bound": "$UPPER_COLORBAR_BOUND"
}
EOF

echo '{"html": {"type": "directory", "name": "html_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Flip_Vertical_Axis --list-values Annotation_s_to_Highlight --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.interactive_spatial_plot_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
