#!/usr/bin/env bash
set -euo pipefail

# Interactive Spatial Plot [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v8.0 (Single run.sh)
# Named argument parsing: --param_name=value format

echo "=== Interactive Spatial Plot [SPAC] [DMAP] ==="

# Copy shared format_values.py from parent directory (if exists)
cp ../format_values.py . 2>/dev/null || true

# Initialize parameters with default values
Stratify_By="None"
Color_By="Annotation"
Annotation_s_to_Highlight="[""]"
Feature_to_Highlight="None"
Table="Original"
Font_Size=12
Dot_Size=1.5
Dot_Transparency=0.75
Flip_Vertical_Axis="False"
Figure_Width=6
Figure_Height=4
Define_Label_Color_Mapping="None"
Figure_DPI=200
Feature_Color_Scale="balance"
Lower_Colorbar_Bound=999
Upper_Colorbar_Bound=-999

# Print received arguments for debugging
echo "Number of arguments: $#"
echo "Arguments received:"
for arg in "$@"; do
    echo "  $arg"
done

# Parse named arguments dynamically (--param_name=value format)
# Based on Conor's example: single pattern handles all --key=value arguments
for arg in "$@"; do
    case "$arg" in
        --*=*)
            key="${arg%%=*}"      # everything before '='
            value="${arg#*=}"     # everything after '='
            key="${key#--}"       # remove leading '--'
            export "$key=$value"
            ;;
    esac
done

# Debug: Print parsed parameter values
echo "Stratify_By: $Stratify_By"
echo "Color_By: $Color_By"
echo "Annotation_s_to_Highlight: $Annotation_s_to_Highlight"
echo "Feature_to_Highlight: $Feature_to_Highlight"
echo "Table: $Table"
echo "Font_Size: $Font_Size"
echo "Dot_Size: $Dot_Size"
echo "Dot_Transparency: $Dot_Transparency"
echo "Flip_Vertical_Axis: $Flip_Vertical_Axis"
echo "Figure_Width: $Figure_Width"
echo "Figure_Height: $Figure_Height"
echo "Define_Label_Color_Mapping: $Define_Label_Color_Mapping"
echo "Figure_DPI: $Figure_DPI"
echo "Feature_Color_Scale: $Feature_Color_Scale"
echo "Lower_Colorbar_Bound: $Lower_Colorbar_Bound"
echo "Upper_Colorbar_Bound: $Upper_Colorbar_Bound"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Stratify_By": "$Stratify_By",
    "Color_By": "$Color_By",
    "Annotation_s_to_Highlight": "$Annotation_s_to_Highlight",
    "Feature_to_Highlight": "$Feature_to_Highlight",
    "Table": "$Table",
    "Font_Size": $Font_Size,
    "Dot_Size": $Dot_Size,
    "Dot_Transparency": $Dot_Transparency,
    "Flip_Vertical_Axis": "$Flip_Vertical_Axis",
    "Figure_Width": $Figure_Width,
    "Figure_Height": $Figure_Height,
    "Define_Label_Color_Mapping": "$Define_Label_Color_Mapping",
    "Figure_DPI": $Figure_DPI,
    "Feature_Color_Scale": "$Feature_Color_Scale",
    "Lower_Colorbar_Bound": $Lower_Colorbar_Bound,
    "Upper_Colorbar_Bound": $Upper_Colorbar_Bound
}
EOF

echo '{"html": {"type": "directory", "name": "html_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Flip_Vertical_Axis --list-values Annotation_s_to_Highlight --inject-outputs --outputs-config /results/jsons/outputs_config.json

echo "Normalized: /results/jsons/params.json -> /results/jsons/cleaned_params.json"

# Run SPAC template
python -c "from spac.templates.interactive_spatial_plot_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json', output_dir='/results')"

echo ""
echo "=== Completed. Outputs in /results/ ==="