#!/usr/bin/env bash
set -euo pipefail

# Setup Analysis [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v8.0 (Single run.sh)
# Named argument parsing: --param_name=value format

echo "=== Setup Analysis [SPAC] [DMAP] ==="

# Copy shared format_values.py from parent directory (if exists)
cp ../format_values.py . 2>/dev/null || true

# Initialize parameters with default values
X_Coordinate_Column="XMax"
Y_Coordinate_Column="YMax"
Annotation_s_="None"
Features_to_Analyze=""
Feature_Regex=""

# Print received arguments for debugging
echo "Number of arguments: $#"
echo "Arguments received:"
for arg in "$@"; do
    echo "  $arg"
done

# Parse named arguments dynamically (--param_name=value format)
# Based on Conor's example: single pattern handles all --key=value arguments
for arg in "$@"; do
    case "$arg" in
        --*=*)
            key="${arg%%=*}"      # everything before '='
            value="${arg#*=}"     # everything after '='
            key="${key#--}"       # remove leading '--'
            export "$key=$value"
            ;;
    esac
done

# Debug: Print parsed parameter values
echo "X_Coordinate_Column: $X_Coordinate_Column"
echo "Y_Coordinate_Column: $Y_Coordinate_Column"
echo "Annotation_s_: $Annotation_s_"
echo "Features_to_Analyze: $Features_to_Analyze"
echo "Feature_Regex: $Feature_Regex"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.csv" -o -name "*.tsv" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Dataset": "$INPUT",
    "X_Coordinate_Column": "$X_Coordinate_Column",
    "Y_Coordinate_Column": "$Y_Coordinate_Column",
    "Annotation_s_": "$Annotation_s_",
    "Features_to_Analyze": "$Features_to_Analyze",
    "Feature_Regex": "$Feature_Regex"
}
EOF

echo '{"analysis": {"type": "file", "name": "output.pickle"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --list-values Features_to_Analyze Feature_Regex Annotation_s_ --inject-outputs --outputs-config /results/jsons/outputs_config.json

echo "Normalized: /results/jsons/params.json -> /results/jsons/cleaned_params.json"

# Run SPAC template
python -c "from spac.templates.setup_analysis_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json', output_dir='/results')"

echo ""
echo "=== Completed. Outputs in /results/ ==="