#!/usr/bin/env bash
set -euo pipefail

# Summarize DataFrame [SPAC][DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Summarize DataFrame [SPAC][DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
PRINT_MISSING_LOCATION="${1:-False}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Print_Missing_Location": "$PRINT_MISSING_LOCATION"
}
EOF

echo '{"html": {"type": "directory", "name": "html_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Print_Missing_Location --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.summarize_dataframe_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
