#!/usr/bin/env bash
set -euo pipefail

# Summarize DataFrame [SPAC][DMAP]
# Generated by code_ocean_synthesizer.py v9.0 (Single run.sh)
# Named argument parsing: --param_name=value format

echo "=== Summarize DataFrame [SPAC][DMAP] ==="

# Copy shared format_values.py from parent directory (if exists)
cp ../format_values.py . 2>/dev/null || true

# Initialize parameters with default values
Print_Missing_Location="False"

# Print received arguments for debugging
echo "Number of arguments: $#"
echo "Arguments received:"
for arg in "$@"; do
    echo "  $arg"
done

# Parse named arguments dynamically (--param_name=value format)
# Single pattern handles all --key=value arguments
for arg in "$@"; do
    case "$arg" in
        --*=*)
            key="${arg%%=*}"      # everything before '='
            value="${arg#*=}"     # everything after '='
            key="${key#--}"       # remove leading '--'
            export "$key=$value"
            ;;
    esac
done

# Debug: Print parsed parameter values
echo "Print_Missing_Location: $Print_Missing_Location"

# Find input data (CSV/TSV)
INPUT=$(find -L ../data -type f \( -name "*.csv" -o -name "*.tsv" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No CSV/TSV file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Dataset": "$INPUT",
    "Print_Missing_Location": "$Print_Missing_Location"
}
EOF

echo '{"html": {"type": "directory", "name": "html_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Print_Missing_Location --inject-outputs --outputs-config /results/jsons/outputs_config.json

echo "Normalized: /results/jsons/params.json -> /results/jsons/cleaned_params.json"

# Run SPAC template
python -c "from spac.templates.summarize_dataframe_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json', output_dir='/results')"

echo ""
echo "=== Completed. Outputs in /results/ ==="