#!/usr/bin/env bash
set -euo pipefail

# Quantile Scaling [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Quantile Scaling [SPAC] [DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
TABLE_TO_PROCESS="${1:-Original}"
LOW_QUANTILE="${2:-0.02}"
HIGH_QUANTILE="${3:-0.98}"
INTERPOLATION="${4:-nearest}"
OUTPUT_TABLE_NAME="${5:-normalized_feature}"
PER_BATCH="${6:-False}"
ANNOTATION="${7:-}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Table_to_Process": "$TABLE_TO_PROCESS",
    "Low_Quantile": "$LOW_QUANTILE",
    "High_Quantile": "$HIGH_QUANTILE",
    "Interpolation": "$INTERPOLATION",
    "Output_Table_Name": "$OUTPUT_TABLE_NAME",
    "Per_Batch": "$PER_BATCH",
    "Annotation": "$ANNOTATION"
}
EOF

echo '{"html": {"type": "directory", "name": "html_dir"}, "analysis": {"type": "file", "name": "output.pickle"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Per_Batch --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.quantile_scaling_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
