#!/usr/bin/env bash
set -euo pipefail

# Post-It-Python [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Post-It-Python [SPAC] [DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
LABEL="${1:-Post-It}"
LABEL_FONT_SIZE="${2:-80}"
LABEL_FONT_TYPE="${3:-normal}"
LABEL_BOLD="${4:-False}"
LABEL_FONT_COLOR="${5:-Black}"
LABEL_FONT_FAMILY="${6:-Arial}"
BACKGROUND_FILL_COLOR="${7:-Yellow1}"
BACKGROUND_FILL_OPACITY="${8:-10}"
PAGE_WIDTH="${9:-18}"
PAGE_HEIGHT="${10:-6}"
PAGE_DPI="${11:-300}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Label": "$LABEL",
    "Label_font_size": "$LABEL_FONT_SIZE",
    "Label_font_type": "$LABEL_FONT_TYPE",
    "Label_Bold": "$LABEL_BOLD",
    "Label_font_color": "$LABEL_FONT_COLOR",
    "Label_font_family": "$LABEL_FONT_FAMILY",
    "Background_fill_color": "$BACKGROUND_FILL_COLOR",
    "Background_fill_opacity": "$BACKGROUND_FILL_OPACITY",
    "Page_width": "$PAGE_WIDTH",
    "Page_height": "$PAGE_HEIGHT",
    "Page_DPI": "$PAGE_DPI"
}
EOF

echo '{"figures": {"type": "directory", "name": "figures_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Label_Bold --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.post_it_python_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
