#!/usr/bin/env bash
set -euo pipefail

# Neighborhood Profile [SPAC][DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Neighborhood Profile [SPAC][DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
ANNOTATION_OF_INTEREST="${1:-}"
BINS="${2:-}"
STRATIFY_BY="${3:-}"
ANCHOR_NEIGHBOR_LIST="${4:-}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Annotation_of_interest": "$ANNOTATION_OF_INTEREST",
    "Bins": "$BINS",
    "Stratify_By": "$STRATIFY_BY",
    "Anchor_Neighbor_List": "$ANCHOR_NEIGHBOR_LIST"
}
EOF

echo '{"dataframe": {"type": "directory", "name": "dataframe_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --list-values Bins Anchor_Neighbor_List --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.neighborhood_profile_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
