#!/usr/bin/env bash
set -euo pipefail

# Histogram [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Histogram [SPAC] [DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
PLOT_BY="${1:-Annotation}"
ANNOTATION="${2:-None}"
TABLE="${3:-Original}"
FEATURE="${4:-None}"
GROUP_BY="${5:-None}"
TOGETHER="${6:-True}"
MULTIPLE="${7:-dodge}"
TAKE_Y_LOG="${8:-False}"
TAKE_X_LOG="${9:-False}"
BINS="${10:-auto}"
SHRINK_NUMBER="${11:-1}"
FIGURE_WIDTH="${12:-8}"
FIGURE_HEIGHT="${13:-6}"
FONT_SIZE="${14:-12}"
FIGURE_DPI="${15:-300}"
LEGEND_IN_FIGURE="${16:-False}"
LEGEND_LOCATION="${17:-best}"
BIN_TRANSPARENCY="${18:-0.75}"
STAT="${19:-count}"
X_AXIS_LABEL_ROTATION="${20:-0}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Plot_By": "$PLOT_BY",
    "Annotation": "$ANNOTATION",
    "Table": "$TABLE",
    "Feature": "$FEATURE",
    "Group_by": "$GROUP_BY",
    "Together": "$TOGETHER",
    "Multiple": "$MULTIPLE",
    "Take_Y_log": "$TAKE_Y_LOG",
    "Take_X_Log": "$TAKE_X_LOG",
    "Bins": "$BINS",
    "Shrink_Number": "$SHRINK_NUMBER",
    "Figure_Width": "$FIGURE_WIDTH",
    "Figure_Height": "$FIGURE_HEIGHT",
    "Font_Size": "$FONT_SIZE",
    "Figure_DPI": "$FIGURE_DPI",
    "Legend_in_Figure": "$LEGEND_IN_FIGURE",
    "Legend_Location": "$LEGEND_LOCATION",
    "Bin_Transparency": "$BIN_TRANSPARENCY",
    "Stat": "$STAT",
    "X_Axis_Label_Rotation": "$X_AXIS_LABEL_ROTATION"
}
EOF

echo '{"dataframe": {"type": "file", "name": "dataframe.csv"}, "figures": {"type": "directory", "name": "figures_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Together Take_Y_log Take_X_Log Legend_in_Figure --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.histogram_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
