#!/usr/bin/env bash
set -euo pipefail

# Histogram [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v9.0 (Single run.sh)
# Named argument parsing: --param_name=value format

echo "=== Histogram [SPAC] [DMAP] ==="

# Copy shared format_values.py from parent directory (if exists)
cp ../format_values.py . 2>/dev/null || true

# Initialize parameters with default values
Plot_By="Annotation"
Annotation="None"
Table="Original"
Feature="None"
Group_by="None"
Together="True"
Multiple="dodge"
Take_Y_log="False"
Take_X_Log="False"
Bins="auto"
Shrink_Number=1
Figure_Width=8
Figure_Height=6
Font_Size=12
Figure_DPI=300
Legend_in_Figure="False"
Legend_Location="best"
Bin_Transparency=0.75
Stat="count"
X_Axis_Label_Rotation=0

# Print received arguments for debugging
echo "Number of arguments: $#"
echo "Arguments received:"
for arg in "$@"; do
    echo "  $arg"
done

# Parse named arguments dynamically (--param_name=value format)
# Single pattern handles all --key=value arguments
for arg in "$@"; do
    case "$arg" in
        --*=*)
            key="${arg%%=*}"      # everything before '='
            value="${arg#*=}"     # everything after '='
            key="${key#--}"       # remove leading '--'
            export "$key=$value"
            ;;
    esac
done

# Debug: Print parsed parameter values
echo "Plot_By: $Plot_By"
echo "Annotation: $Annotation"
echo "Table: $Table"
echo "Feature: $Feature"
echo "Group_by: $Group_by"
echo "Together: $Together"
echo "Multiple: $Multiple"
echo "Take_Y_log: $Take_Y_log"
echo "Take_X_Log: $Take_X_Log"
echo "Bins: $Bins"
echo "Shrink_Number: $Shrink_Number"
echo "Figure_Width: $Figure_Width"
echo "Figure_Height: $Figure_Height"
echo "Font_Size: $Font_Size"
echo "Figure_DPI: $Figure_DPI"
echo "Legend_in_Figure: $Legend_in_Figure"
echo "Legend_Location: $Legend_Location"
echo "Bin_Transparency: $Bin_Transparency"
echo "Stat: $Stat"
echo "X_Axis_Label_Rotation: $X_Axis_Label_Rotation"

# Find input data (pickle/pkl/h5ad)
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No pickle/pkl/h5ad file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Plot_By": "$Plot_By",
    "Annotation": "$Annotation",
    "Table": "$Table",
    "Feature": "$Feature",
    "Group_by": "$Group_by",
    "Together": "$Together",
    "Multiple": "$Multiple",
    "Take_Y_log": "$Take_Y_log",
    "Take_X_Log": "$Take_X_Log",
    "Bins": "$Bins",
    "Shrink_Number": $Shrink_Number,
    "Figure_Width": $Figure_Width,
    "Figure_Height": $Figure_Height,
    "Font_Size": $Font_Size,
    "Figure_DPI": $Figure_DPI,
    "Legend_in_Figure": "$Legend_in_Figure",
    "Legend_Location": "$Legend_Location",
    "Bin_Transparency": $Bin_Transparency,
    "Stat": "$Stat",
    "X_Axis_Label_Rotation": $X_Axis_Label_Rotation
}
EOF

echo '{"dataframe": {"type": "file", "name": "dataframe.csv"}, "figures": {"type": "directory", "name": "figures_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Together Take_Y_log Take_X_Log Legend_in_Figure --inject-outputs --outputs-config /results/jsons/outputs_config.json

echo "Normalized: /results/jsons/params.json -> /results/jsons/cleaned_params.json"

# Run SPAC template
python -c "from spac.templates.histogram_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json', output_dir='/results')"

echo ""
echo "=== Completed. Outputs in /results/ ==="