#!/usr/bin/env bash
set -euo pipefail

# Nearest Neighbor Calculation [SPAC][DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Nearest Neighbor Calculation [SPAC][DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
ANNOTATION="${1:-}"
IMAGEID="${2:-None}"
NEAREST_NEIGHBOR_ASSOCIATED_TABLE="${3:-spatial_distance}"
VERBOSE="${4:-True}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Annotation": "$ANNOTATION",
    "ImageID": "$IMAGEID",
    "Nearest_Neighbor_Associated_Table": "$NEAREST_NEIGHBOR_ASSOCIATED_TABLE",
    "Verbose": "$VERBOSE"
}
EOF

echo '{"analysis": {"type": "file", "name": "output.pickle"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Verbose --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.nearest_neighbor_calculation_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
