#!/usr/bin/env bash
set -euo pipefail

# Rename Labels [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Rename Labels [SPAC] [DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
SOURCE_ANNOTATION="${1:-None}"
NEW_ANNOTATION="${2:-None}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Source_Annotation": "$SOURCE_ANNOTATION",
    "New_Annotation": "$NEW_ANNOTATION"
}
EOF

echo '{"analysis": {"type": "file", "name": "output.pickle"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.rename_labels_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
