#!/usr/bin/env bash
set -euo pipefail

# Rename Labels [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v9.0 (Single run.sh)
# Named argument parsing: --param_name=value format

echo "=== Rename Labels [SPAC] [DMAP] ==="

# Copy shared format_values.py from parent directory (if exists)
cp ../format_values.py . 2>/dev/null || true

# Initialize parameters with default values
Upstream_Analysis_Pattern="*"
Cluster_Mapping_Dictionary_Pattern="*input2*"
Source_Annotation="None"
New_Annotation="None"

# Print received arguments for debugging
echo "Number of arguments: $#"
echo "Arguments received:"
for arg in "$@"; do
    echo "  $arg"
done

# Parse named arguments dynamically (--param_name=value format)
# Single pattern handles all --key=value arguments
for arg in "$@"; do
    case "$arg" in
        --*=*)
            key="${arg%%=*}"      # everything before '='
            value="${arg#*=}"     # everything after '='
            key="${key#--}"       # remove leading '--'
            export "$key=$value"
            ;;
    esac
done

# Debug: Print parsed parameter values
echo "Upstream_Analysis_Pattern: $Upstream_Analysis_Pattern"
echo "Cluster_Mapping_Dictionary_Pattern: $Cluster_Mapping_Dictionary_Pattern"
echo "Source_Annotation: $Source_Annotation"
echo "New_Annotation: $New_Annotation"

# Find Upstream Analysis (pickle/pkl/h5ad)
echo "Searching for Upstream Analysis matching pattern: $Upstream_Analysis_Pattern"
INPUT_1=$(find -L ../data -type f \( -name "$Upstream_Analysis_Pattern.pickle" -o -name "$Upstream_Analysis_Pattern.pkl" -o -name "$Upstream_Analysis_Pattern.h5ad" \) 2>/dev/null | head -n 1)
# Fallback: try pattern as-is
if [ -z "$INPUT_1" ]; then INPUT_1=$(find -L ../data -type f -name "$Upstream_Analysis_Pattern" 2>/dev/null | head -n 1); fi
if [ -z "$INPUT_1" ]; then echo "ERROR: No Upstream Analysis found matching pattern: $Upstream_Analysis_Pattern"; exit 1; fi
echo "Upstream Analysis: $INPUT_1"

# Find Cluster Mapping Dictionary (CSV/TSV)
echo "Searching for Cluster Mapping Dictionary matching pattern: $Cluster_Mapping_Dictionary_Pattern"
INPUT_2=$(find -L ../data -type f \( -name "$Cluster_Mapping_Dictionary_Pattern.csv" -o -name "$Cluster_Mapping_Dictionary_Pattern.tsv" \) 2>/dev/null | head -n 1)
# Fallback: try pattern as-is
if [ -z "$INPUT_2" ]; then INPUT_2=$(find -L ../data -type f -name "$Cluster_Mapping_Dictionary_Pattern" 2>/dev/null | head -n 1); fi
if [ -z "$INPUT_2" ]; then echo "ERROR: No Cluster Mapping Dictionary found matching pattern: $Cluster_Mapping_Dictionary_Pattern"; exit 1; fi
echo "Cluster Mapping Dictionary: $INPUT_2"


# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT_1",
    "Cluster_Mapping_Dictionary": "$INPUT_2",
    "Source_Annotation": "$Source_Annotation",
    "New_Annotation": "$New_Annotation"
}
EOF

echo '{"analysis": {"type": "file", "name": "output.pickle"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --inject-outputs --outputs-config /results/jsons/outputs_config.json

echo "Normalized: /results/jsons/params.json -> /results/jsons/cleaned_params.json"

# Run SPAC template
python -c "from spac.templates.rename_labels_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json', output_dir='/results')"

echo ""
echo "=== Completed. Outputs in /results/ ==="