#!/usr/bin/env bash
set -euo pipefail

# Sankey Plot [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Sankey Plot [SPAC] [DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
SOURCE_ANNOTATION_NAME="${1:-None}"
TARGET_ANNOTATION_NAME="${2:-None}"
SOURCE_ANNOTATION_COLOR_MAP="${3:-tab20}"
TARGET_ANNOTATION_COLOR_MAP="${4:-tab20b}"
FIGURE_WIDTH_INCH="${5:-6}"
FIGURE_HEIGHT_INCH="${6:-6}"
FIGURE_DPI="${7:-300}"
FONT_SIZE="${8:-12}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Source_Annotation_Name": "$SOURCE_ANNOTATION_NAME",
    "Target_Annotation_Name": "$TARGET_ANNOTATION_NAME",
    "Source_Annotation_Color_Map": "$SOURCE_ANNOTATION_COLOR_MAP",
    "Target_Annotation_Color_Map": "$TARGET_ANNOTATION_COLOR_MAP",
    "Figure_Width_inch": "$FIGURE_WIDTH_INCH",
    "Figure_Height_inch": "$FIGURE_HEIGHT_INCH",
    "Figure_DPI": "$FIGURE_DPI",
    "Font_Size": "$FONT_SIZE"
}
EOF

echo '{"figures": {"type": "directory", "name": "figures_dir"}, "html": {"type": "directory", "name": "html_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.sankey_plot_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
