#!/usr/bin/env bash
set -euo pipefail

# Sankey Plot [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v8.0 (Single run.sh)
# Named argument parsing: --param_name=value format

echo "=== Sankey Plot [SPAC] [DMAP] ==="

# Copy shared format_values.py from parent directory (if exists)
cp ../format_values.py . 2>/dev/null || true

# Initialize parameters with default values
Source_Annotation_Name="None"
Target_Annotation_Name="None"
Source_Annotation_Color_Map="tab20"
Target_Annotation_Color_Map="tab20b"
Figure_Width_inch=6
Figure_Height_inch=6
Figure_DPI=300
Font_Size=12

# Print received arguments for debugging
echo "Number of arguments: $#"
echo "Arguments received:"
for arg in "$@"; do
    echo "  $arg"
done

# Parse named arguments dynamically (--param_name=value format)
# Based on Conor's example: single pattern handles all --key=value arguments
for arg in "$@"; do
    case "$arg" in
        --*=*)
            key="${arg%%=*}"      # everything before '='
            value="${arg#*=}"     # everything after '='
            key="${key#--}"       # remove leading '--'
            export "$key=$value"
            ;;
    esac
done

# Debug: Print parsed parameter values
echo "Source_Annotation_Name: $Source_Annotation_Name"
echo "Target_Annotation_Name: $Target_Annotation_Name"
echo "Source_Annotation_Color_Map: $Source_Annotation_Color_Map"
echo "Target_Annotation_Color_Map: $Target_Annotation_Color_Map"
echo "Figure_Width_inch: $Figure_Width_inch"
echo "Figure_Height_inch: $Figure_Height_inch"
echo "Figure_DPI: $Figure_DPI"
echo "Font_Size: $Font_Size"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Source_Annotation_Name": "$Source_Annotation_Name",
    "Target_Annotation_Name": "$Target_Annotation_Name",
    "Source_Annotation_Color_Map": "$Source_Annotation_Color_Map",
    "Target_Annotation_Color_Map": "$Target_Annotation_Color_Map",
    "Figure_Width_inch": $Figure_Width_inch,
    "Figure_Height_inch": $Figure_Height_inch,
    "Figure_DPI": $Figure_DPI,
    "Font_Size": $Font_Size
}
EOF

echo '{"figures": {"type": "directory", "name": "figures_dir"}, "html": {"type": "directory", "name": "html_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --inject-outputs --outputs-config /results/jsons/outputs_config.json

echo "Normalized: /results/jsons/params.json -> /results/jsons/cleaned_params.json"

# Run SPAC template
python -c "from spac.templates.sankey_plot_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json', output_dir='/results')"

echo ""
echo "=== Completed. Outputs in /results/ ==="