#!/usr/bin/env bash
set -euo pipefail

# UMAP\tSNE\PCA Visualization [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== UMAP\tSNE\PCA Visualization [SPAC] [DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
COLOR_BY="${1:-Annotation}"
ANNOTATION_TO_HIGHLIGHT="${2:-None}"
TABLE="${3:-Original}"
FEATURE_TO_HIGHLIGHT="${4:-None}"
DIMENSION_REDUCTION_METHOD="${5:-umap}"
DOT_SIZE="${6:-1}"
FIGURE_WIDTH="${7:-12}"
FIGURE_HEIGHT="${8:-12}"
FONT_SIZE="${9:-12}"
FIGURE_DPI="${10:-300}"
LEGEND_LOCATION="${11:-best}"
LEGEND_FONT_SIZE="${12:-16}"
LEGEND_MARKER_SIZE="${13:-5.0}"
VALUE_MIN="${14:-None}"
VALUE_MAX="${15:-None}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Color_By": "$COLOR_BY",
    "Annotation_to_Highlight": "$ANNOTATION_TO_HIGHLIGHT",
    "Table": "$TABLE",
    "Feature_to_Highlight": "$FEATURE_TO_HIGHLIGHT",
    "Dimension_Reduction_Method": "$DIMENSION_REDUCTION_METHOD",
    "Dot_Size": "$DOT_SIZE",
    "Figure_Width": "$FIGURE_WIDTH",
    "Figure_Height": "$FIGURE_HEIGHT",
    "Font_Size": "$FONT_SIZE",
    "Figure_DPI": "$FIGURE_DPI",
    "Legend_Location": "$LEGEND_LOCATION",
    "Legend_Font_Size": "$LEGEND_FONT_SIZE",
    "Legend_Marker_Size": "$LEGEND_MARKER_SIZE",
    "Value_Min": "$VALUE_MIN",
    "Value_Max": "$VALUE_MAX"
}
EOF

echo '{"figures": {"type": "directory", "name": "figures_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.umaptsnepca_visualization_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
