#!/usr/bin/env bash
set -euo pipefail

# Spatial Plot [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Spatial Plot [SPAC] [DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
STRATIFY="${1:-True}"
STRATIFY_BY="${2:-[]}"
COLOR_BY="${3:-Annotation}"
ANNOTATION_TO_HIGHLIGHT="${4:-None}"
TABLE="${5:-Original}"
FEATURE_TO_HIGHLIGHT="${6:-}"
UPPER_COLORBAR_BOUND="${7:--999}"
LOWER_COLORBAR_BOUND="${8:-999}"
DOT_SIZE="${9:-25}"
FIGURE_HEIGHT="${10:-6}"
DOT_TRANSPARENCY="${11:-0.5}"
FONT_SIZE="${12:-12}"
FIGURE_WIDTH="${13:-12}"
FIGURE_DPI="${14:-200}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Stratify": "$STRATIFY",
    "Stratify_By": "$STRATIFY_BY",
    "Color_By": "$COLOR_BY",
    "Annotation_to_Highlight": "$ANNOTATION_TO_HIGHLIGHT",
    "Table": "$TABLE",
    "Feature_to_Highlight": "$FEATURE_TO_HIGHLIGHT",
    "Upper_Colorbar_Bound": "$UPPER_COLORBAR_BOUND",
    "Lower_Colorbar_Bound": "$LOWER_COLORBAR_BOUND",
    "Dot_Size": "$DOT_SIZE",
    "Figure_Height": "$FIGURE_HEIGHT",
    "Dot_Transparency": "$DOT_TRANSPARENCY",
    "Font_Size": "$FONT_SIZE",
    "Figure_Width": "$FIGURE_WIDTH",
    "Figure_DPI": "$FIGURE_DPI"
}
EOF

echo '{"figures": {"type": "directory", "name": "figures_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Stratify --list-values Stratify_By --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.spatial_plot_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
