#!/usr/bin/env bash
set -euo pipefail

# Spatial Plot [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v9.0 (Single run.sh)
# Named argument parsing: --param_name=value format

echo "=== Spatial Plot [SPAC] [DMAP] ==="

# Copy shared format_values.py from parent directory (if exists)
cp ../format_values.py . 2>/dev/null || true

# Initialize parameters with default values
Stratify="True"
Stratify_By="[]"
Color_By="Annotation"
Annotation_to_Highlight="None"
Table="Original"
Feature_to_Highlight=""
Upper_Colorbar_Bound=-999
Lower_Colorbar_Bound=999
Dot_Size=25
Figure_Height=6
Dot_Transparency=0.5
Font_Size=12
Figure_Width=12
Figure_DPI=200

# Print received arguments for debugging
echo "Number of arguments: $#"
echo "Arguments received:"
for arg in "$@"; do
    echo "  $arg"
done

# Parse named arguments dynamically (--param_name=value format)
# Single pattern handles all --key=value arguments
for arg in "$@"; do
    case "$arg" in
        --*=*)
            key="${arg%%=*}"      # everything before '='
            value="${arg#*=}"     # everything after '='
            key="${key#--}"       # remove leading '--'
            export "$key=$value"
            ;;
    esac
done

# Debug: Print parsed parameter values
echo "Stratify: $Stratify"
echo "Stratify_By: $Stratify_By"
echo "Color_By: $Color_By"
echo "Annotation_to_Highlight: $Annotation_to_Highlight"
echo "Table: $Table"
echo "Feature_to_Highlight: $Feature_to_Highlight"
echo "Upper_Colorbar_Bound: $Upper_Colorbar_Bound"
echo "Lower_Colorbar_Bound: $Lower_Colorbar_Bound"
echo "Dot_Size: $Dot_Size"
echo "Figure_Height: $Figure_Height"
echo "Dot_Transparency: $Dot_Transparency"
echo "Font_Size: $Font_Size"
echo "Figure_Width: $Figure_Width"
echo "Figure_DPI: $Figure_DPI"

# Find input data (pickle/pkl/h5ad)
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No pickle/pkl/h5ad file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Stratify": "$Stratify",
    "Stratify_By": "$Stratify_By",
    "Color_By": "$Color_By",
    "Annotation_to_Highlight": "$Annotation_to_Highlight",
    "Table": "$Table",
    "Feature_to_Highlight": "$Feature_to_Highlight",
    "Upper_Colorbar_Bound": $Upper_Colorbar_Bound,
    "Lower_Colorbar_Bound": $Lower_Colorbar_Bound,
    "Dot_Size": $Dot_Size,
    "Figure_Height": $Figure_Height,
    "Dot_Transparency": $Dot_Transparency,
    "Font_Size": $Font_Size,
    "Figure_Width": $Figure_Width,
    "Figure_DPI": $Figure_DPI
}
EOF

echo '{"figures": {"type": "directory", "name": "figures_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Stratify --list-values Stratify_By --inject-outputs --outputs-config /results/jsons/outputs_config.json

echo "Normalized: /results/jsons/params.json -> /results/jsons/cleaned_params.json"

# Run SPAC template
python -c "from spac.templates.spatial_plot_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json', output_dir='/results')"

echo ""
echo "=== Completed. Outputs in /results/ ==="