#!/usr/bin/env bash
set -euo pipefail

# Ripley L Calculation [SPAC][DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Ripley L Calculation [SPAC][DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
RADII="${1:-["0","5","10"]}"
ANNOTATION="${2:-}"
CENTER_PHENOTYPE="${3:-}"
NEIGHBOR_PHENOTYPE="${4:-}"
STRATIFY_BY="${5:-None}"
NUMBER_OF_SIMULATIONS="${6:-1}"
AREA="${7:-None}"
SEED="${8:-42}"
EDGE_CORRECTION="${9:-True}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Radii": "$RADII",
    "Annotation": "$ANNOTATION",
    "Center_Phenotype": "$CENTER_PHENOTYPE",
    "Neighbor_Phenotype": "$NEIGHBOR_PHENOTYPE",
    "Stratify_By": "$STRATIFY_BY",
    "Number_of_Simulations": "$NUMBER_OF_SIMULATIONS",
    "Area": "$AREA",
    "Seed": "$SEED",
    "Edge_Correction": "$EDGE_CORRECTION"
}
EOF

echo '{"analysis": {"type": "file", "name": "output.pickle"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Edge_Correction --list-values Radii --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.ripley_l_calculation_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
