#!/usr/bin/env bash
set -euo pipefail

# Ripley L Calculation [SPAC][DMAP]
# Generated by code_ocean_synthesizer.py v8.0 (Single run.sh)
# Named argument parsing: --param_name=value format

echo "=== Ripley L Calculation [SPAC][DMAP] ==="

# Copy shared format_values.py from parent directory (if exists)
cp ../format_values.py . 2>/dev/null || true

# Initialize parameters with default values
Radii="["0","5","10"]"
Annotation=""
Center_Phenotype=""
Neighbor_Phenotype=""
Stratify_By="None"
Number_of_Simulations=1
Area="None"
Seed=42
Edge_Correction="True"

# Print received arguments for debugging
echo "Number of arguments: $#"
echo "Arguments received:"
for arg in "$@"; do
    echo "  $arg"
done

# Parse named arguments dynamically (--param_name=value format)
# Based on Conor's example: single pattern handles all --key=value arguments
for arg in "$@"; do
    case "$arg" in
        --*=*)
            key="${arg%%=*}"      # everything before '='
            value="${arg#*=}"     # everything after '='
            key="${key#--}"       # remove leading '--'
            export "$key=$value"
            ;;
    esac
done

# Debug: Print parsed parameter values
echo "Radii: $Radii"
echo "Annotation: $Annotation"
echo "Center_Phenotype: $Center_Phenotype"
echo "Neighbor_Phenotype: $Neighbor_Phenotype"
echo "Stratify_By: $Stratify_By"
echo "Number_of_Simulations: $Number_of_Simulations"
echo "Area: $Area"
echo "Seed: $Seed"
echo "Edge_Correction: $Edge_Correction"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Radii": "$Radii",
    "Annotation": "$Annotation",
    "Center_Phenotype": "$Center_Phenotype",
    "Neighbor_Phenotype": "$Neighbor_Phenotype",
    "Stratify_By": "$Stratify_By",
    "Number_of_Simulations": $Number_of_Simulations,
    "Area": "$Area",
    "Seed": $Seed,
    "Edge_Correction": "$Edge_Correction"
}
EOF

echo '{"analysis": {"type": "file", "name": "output.pickle"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Edge_Correction --list-values Radii --inject-outputs --outputs-config /results/jsons/outputs_config.json

echo "Normalized: /results/jsons/params.json -> /results/jsons/cleaned_params.json"

# Run SPAC template
python -c "from spac.templates.ripley_l_calculation_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json', output_dir='/results')"

echo ""
echo "=== Completed. Outputs in /results/ ==="