#!/usr/bin/env bash
set -euo pipefail

# Downsample Cells [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Downsample Cells [SPAC] [DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
NUMBER_OF_SAMPLES="${1:-100000}"
STRATIFY_OPTION="${2:-False}"
RANDOM_SELECTION="${3:-True}"
NEW_COMBINED_ANNOTATION_NAME="${4:-_combined_}"
MINIMUM_THRESHOLD="${5:-5}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Number_of_Samples": "$NUMBER_OF_SAMPLES",
    "Stratify_Option": "$STRATIFY_OPTION",
    "Random_Selection": "$RANDOM_SELECTION",
    "New_Combined_Annotation_Name": "$NEW_COMBINED_ANNOTATION_NAME",
    "Minimum_Threshold": "$MINIMUM_THRESHOLD"
}
EOF

echo '{"dataframe": {"type": "file", "name": "dataframe.csv"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Stratify_Option Random_Selection --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.downsample_cells_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
