#!/usr/bin/env bash
set -euo pipefail

# Manual Phenotyping [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Manual Phenotyping [SPAC] [DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
CLASSIFICATION_COLUMN_PREFIX="${1:-}"
CLASSIFICATION_COLUMN_SUFFIX="${2:-}"
ALLOW_MULTIPLE_PHENOTYPES="${3:-True}"
MANUAL_ANNOTATION_NAME="${4:-manual_phenotype}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Classification_Column_Prefix": "$CLASSIFICATION_COLUMN_PREFIX",
    "Classification_Column_Suffix": "$CLASSIFICATION_COLUMN_SUFFIX",
    "Allow_Multiple_Phenotypes": "$ALLOW_MULTIPLE_PHENOTYPES",
    "Manual_Annotation_Name": "$MANUAL_ANNOTATION_NAME"
}
EOF

echo '{"dataframe": {"type": "file", "name": "dataframe.csv"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Allow_Multiple_Phenotypes --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.manual_phenotyping_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
