#!/usr/bin/env bash
set -euo pipefail

# Manual Phenotyping [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v9.0 (Single run.sh)
# Named argument parsing: --param_name=value format

echo "=== Manual Phenotyping [SPAC] [DMAP] ==="

# Copy shared format_values.py from parent directory (if exists)
cp ../format_values.py . 2>/dev/null || true

# Initialize parameters with default values
Upstream_Dataset_Pattern="*"
Phenotypes_Code_Pattern="*input2*"
Classification_Column_Prefix=""
Classification_Column_Suffix=""
Allow_Multiple_Phenotypes="True"
Manual_Annotation_Name="manual_phenotype"

# Print received arguments for debugging
echo "Number of arguments: $#"
echo "Arguments received:"
for arg in "$@"; do
    echo "  $arg"
done

# Parse named arguments dynamically (--param_name=value format)
# Single pattern handles all --key=value arguments
for arg in "$@"; do
    case "$arg" in
        --*=*)
            key="${arg%%=*}"      # everything before '='
            value="${arg#*=}"     # everything after '='
            key="${key#--}"       # remove leading '--'
            export "$key=$value"
            ;;
    esac
done

# Debug: Print parsed parameter values
echo "Upstream_Dataset_Pattern: $Upstream_Dataset_Pattern"
echo "Phenotypes_Code_Pattern: $Phenotypes_Code_Pattern"
echo "Classification_Column_Prefix: $Classification_Column_Prefix"
echo "Classification_Column_Suffix: $Classification_Column_Suffix"
echo "Allow_Multiple_Phenotypes: $Allow_Multiple_Phenotypes"
echo "Manual_Annotation_Name: $Manual_Annotation_Name"

# Find Upstream Dataset (CSV/TSV)
echo "Searching for Upstream Dataset matching pattern: $Upstream_Dataset_Pattern"
INPUT_1=$(find -L ../data -type f \( -name "$Upstream_Dataset_Pattern.csv" -o -name "$Upstream_Dataset_Pattern.tsv" \) 2>/dev/null | head -n 1)
# Fallback: try pattern as-is
if [ -z "$INPUT_1" ]; then INPUT_1=$(find -L ../data -type f -name "$Upstream_Dataset_Pattern" 2>/dev/null | head -n 1); fi
if [ -z "$INPUT_1" ]; then echo "ERROR: No Upstream Dataset found matching pattern: $Upstream_Dataset_Pattern"; exit 1; fi
echo "Upstream Dataset: $INPUT_1"

# Find Phenotypes Code (CSV/TSV)
echo "Searching for Phenotypes Code matching pattern: $Phenotypes_Code_Pattern"
INPUT_2=$(find -L ../data -type f \( -name "$Phenotypes_Code_Pattern.csv" -o -name "$Phenotypes_Code_Pattern.tsv" \) 2>/dev/null | head -n 1)
# Fallback: try pattern as-is
if [ -z "$INPUT_2" ]; then INPUT_2=$(find -L ../data -type f -name "$Phenotypes_Code_Pattern" 2>/dev/null | head -n 1); fi
if [ -z "$INPUT_2" ]; then echo "ERROR: No Phenotypes Code found matching pattern: $Phenotypes_Code_Pattern"; exit 1; fi
echo "Phenotypes Code: $INPUT_2"


# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Dataset": "$INPUT_1",
    "Phenotypes_Code": "$INPUT_2",
    "Classification_Column_Prefix": "$Classification_Column_Prefix",
    "Classification_Column_Suffix": "$Classification_Column_Suffix",
    "Allow_Multiple_Phenotypes": "$Allow_Multiple_Phenotypes",
    "Manual_Annotation_Name": "$Manual_Annotation_Name"
}
EOF

echo '{"dataframe": {"type": "file", "name": "dataframe.csv"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Allow_Multiple_Phenotypes --inject-outputs --outputs-config /results/jsons/outputs_config.json

echo "Normalized: /results/jsons/params.json -> /results/jsons/cleaned_params.json"

# Run SPAC template
python -c "from spac.templates.manual_phenotyping_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json', output_dir='/results')"

echo ""
echo "=== Completed. Outputs in /results/ ==="