#!/usr/bin/env bash
set -euo pipefail

# Boxplot [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Boxplot [SPAC] [DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
TABLE_TO_VISUALIZE="${1:-Original}"
FEATURE_S_TO_PLOT="${2:-All}"
PRIMARY_ANNOTATION="${3:-None}"
SECONDARY_ANNOTATION="${4:-None}"
VALUE_AXIS_LOG_SCALE="${5:-False}"
FIGURE_TITLE="${6:-BoxPlot}"
HORIZONTAL_PLOT="${7:-False}"
FIGURE_WIDTH="${8:-12}"
FIGURE_HEIGHT="${9:-8}"
FIGURE_DPI="${10:-300}"
FONT_SIZE="${11:-10}"
KEEP_OUTLIERS="${12:-True}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Table_to_Visualize": "$TABLE_TO_VISUALIZE",
    "Feature_s_to_Plot": "$FEATURE_S_TO_PLOT",
    "Primary_Annotation": "$PRIMARY_ANNOTATION",
    "Secondary_Annotation": "$SECONDARY_ANNOTATION",
    "Value_Axis_Log_Scale": "$VALUE_AXIS_LOG_SCALE",
    "Figure_Title": "$FIGURE_TITLE",
    "Horizontal_Plot": "$HORIZONTAL_PLOT",
    "Figure_Width": "$FIGURE_WIDTH",
    "Figure_Height": "$FIGURE_HEIGHT",
    "Figure_DPI": "$FIGURE_DPI",
    "Font_Size": "$FONT_SIZE",
    "Keep_Outliers": "$KEEP_OUTLIERS"
}
EOF

echo '{"dataframe": {"type": "file", "name": "dataframe.csv"}, "figures": {"type": "directory", "name": "figures_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Value_Axis_Log_Scale Horizontal_Plot Keep_Outliers --list-values Feature_s_to_Plot --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.boxplot_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
