#!/usr/bin/env bash
set -euo pipefail

# Boxplot [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v8.0 (Single run.sh)
# Named argument parsing: --param_name=value format

echo "=== Boxplot [SPAC] [DMAP] ==="

# Copy shared format_values.py from parent directory (if exists)
cp ../format_values.py . 2>/dev/null || true

# Initialize parameters with default values
Table_to_Visualize="Original"
Feature_s_to_Plot="All"
Primary_Annotation="None"
Secondary_Annotation="None"
Value_Axis_Log_Scale="False"
Figure_Title="BoxPlot"
Horizontal_Plot="False"
Figure_Width=12
Figure_Height=8
Figure_DPI=300
Font_Size=10
Keep_Outliers="True"

# Print received arguments for debugging
echo "Number of arguments: $#"
echo "Arguments received:"
for arg in "$@"; do
    echo "  $arg"
done

# Parse named arguments dynamically (--param_name=value format)
# Based on Conor's example: single pattern handles all --key=value arguments
for arg in "$@"; do
    case "$arg" in
        --*=*)
            key="${arg%%=*}"      # everything before '='
            value="${arg#*=}"     # everything after '='
            key="${key#--}"       # remove leading '--'
            export "$key=$value"
            ;;
    esac
done

# Debug: Print parsed parameter values
echo "Table_to_Visualize: $Table_to_Visualize"
echo "Feature_s_to_Plot: $Feature_s_to_Plot"
echo "Primary_Annotation: $Primary_Annotation"
echo "Secondary_Annotation: $Secondary_Annotation"
echo "Value_Axis_Log_Scale: $Value_Axis_Log_Scale"
echo "Figure_Title: $Figure_Title"
echo "Horizontal_Plot: $Horizontal_Plot"
echo "Figure_Width: $Figure_Width"
echo "Figure_Height: $Figure_Height"
echo "Figure_DPI: $Figure_DPI"
echo "Font_Size: $Font_Size"
echo "Keep_Outliers: $Keep_Outliers"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Table_to_Visualize": "$Table_to_Visualize",
    "Feature_s_to_Plot": "$Feature_s_to_Plot",
    "Primary_Annotation": "$Primary_Annotation",
    "Secondary_Annotation": "$Secondary_Annotation",
    "Value_Axis_Log_Scale": "$Value_Axis_Log_Scale",
    "Figure_Title": "$Figure_Title",
    "Horizontal_Plot": "$Horizontal_Plot",
    "Figure_Width": $Figure_Width,
    "Figure_Height": $Figure_Height,
    "Figure_DPI": $Figure_DPI,
    "Font_Size": $Font_Size,
    "Keep_Outliers": "$Keep_Outliers"
}
EOF

echo '{"dataframe": {"type": "file", "name": "dataframe.csv"}, "figures": {"type": "directory", "name": "figures_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Value_Axis_Log_Scale Horizontal_Plot Keep_Outliers --list-values Feature_s_to_Plot --inject-outputs --outputs-config /results/jsons/outputs_config.json

echo "Normalized: /results/jsons/params.json -> /results/jsons/cleaned_params.json"

# Run SPAC template
python -c "from spac.templates.boxplot_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json', output_dir='/results')"

echo ""
echo "=== Completed. Outputs in /results/ ==="