#!/usr/bin/env bash
set -euo pipefail

# Post-It-Python [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v9.0 (Single run.sh)
# Named argument parsing: --param_name=value format

echo "=== Post-It-Python [SPAC] [DMAP] ==="

# Copy shared format_values.py from parent directory (if exists)
cp ../format_values.py . 2>/dev/null || true

# Initialize parameters with default values
Label="Post-It"
Label_font_size=80
Label_font_type="normal"
Label_Bold="False"
Label_font_color="Black"
Label_font_family="Arial"
Background_fill_color="Yellow1"
Background_fill_opacity=10
Page_width=18
Page_height=6
Page_DPI=300

# Print received arguments for debugging
echo "Number of arguments: $#"
echo "Arguments received:"
for arg in "$@"; do
    echo "  $arg"
done

# Parse named arguments dynamically (--param_name=value format)
# Single pattern handles all --key=value arguments
for arg in "$@"; do
    case "$arg" in
        --*=*)
            key="${arg%%=*}"      # everything before '='
            value="${arg#*=}"     # everything after '='
            key="${key#--}"       # remove leading '--'
            export "$key=$value"
            ;;
    esac
done

# Debug: Print parsed parameter values
echo "Label: $Label"
echo "Label_font_size: $Label_font_size"
echo "Label_font_type: $Label_font_type"
echo "Label_Bold: $Label_Bold"
echo "Label_font_color: $Label_font_color"
echo "Label_font_family: $Label_font_family"
echo "Background_fill_color: $Background_fill_color"
echo "Background_fill_opacity: $Background_fill_opacity"
echo "Page_width: $Page_width"
echo "Page_height: $Page_height"
echo "Page_DPI: $Page_DPI"

# Find input data (pickle/pkl/h5ad)
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No pickle/pkl/h5ad file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Label": "$Label",
    "Label_font_size": $Label_font_size,
    "Label_font_type": "$Label_font_type",
    "Label_Bold": "$Label_Bold",
    "Label_font_color": "$Label_font_color",
    "Label_font_family": "$Label_font_family",
    "Background_fill_color": "$Background_fill_color",
    "Background_fill_opacity": $Background_fill_opacity,
    "Page_width": $Page_width,
    "Page_height": $Page_height,
    "Page_DPI": $Page_DPI
}
EOF

echo '{"figures": {"type": "directory", "name": "figures_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Label_Bold --inject-outputs --outputs-config /results/jsons/outputs_config.json

echo "Normalized: /results/jsons/params.json -> /results/jsons/cleaned_params.json"

# Run SPAC template
python -c "from spac.templates.post_it_python_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json', output_dir='/results')"

echo ""
echo "=== Completed. Outputs in /results/ ==="