#!/usr/bin/env bash
set -euo pipefail

# UMAP Transformation [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== UMAP Transformation [SPAC] [DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
RUN_ON_HPC="${1:-False}"
TABLE_TO_PROCESS="${2:-Original}"
NUMBER_OF_NEIGHBORS="${3:-75}"
TARGET_DIMENSION_NUMBER="${4:-2}"
MINIMUM_DISTANCE_BETWEEN_POINTS="${5:-0.1}"
COMPUTATIONAL_METRIC="${6:-euclidean}"
TRANSFORM_SEED="${7:-42}"
RANDOM_STATE="${8:-0}"
BATCH_MODE="${9:-False}"
PARTITION="${10:-quick}"
NUMBER_OF_CPUS="${11:-2}"
MEMORY_GB="${12:-10}"
REQUEST_TIME="${13:-00:20:00}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Run_on_HPC": "$RUN_ON_HPC",
    "Table_to_Process": "$TABLE_TO_PROCESS",
    "Number_of_Neighbors": "$NUMBER_OF_NEIGHBORS",
    "Target_Dimension_Number": "$TARGET_DIMENSION_NUMBER",
    "Minimum_Distance_between_Points": "$MINIMUM_DISTANCE_BETWEEN_POINTS",
    "Computational_Metric": "$COMPUTATIONAL_METRIC",
    "Transform_Seed": "$TRANSFORM_SEED",
    "Random_State": "$RANDOM_STATE",
    "Batch_Mode": "$BATCH_MODE",
    "Partition": "$PARTITION",
    "Number_of_CPUs": "$NUMBER_OF_CPUS",
    "Memory_GB": "$MEMORY_GB",
    "Request_Time": "$REQUEST_TIME"
}
EOF

echo '{"analysis": {"type": "file", "name": "output.pickle"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Run_on_HPC Batch_Mode --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.umap_transformation_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
