#!/usr/bin/env bash
set -euo pipefail

# UMAP Transformation [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v8.0 (Single run.sh)
# Named argument parsing: --param_name=value format

echo "=== UMAP Transformation [SPAC] [DMAP] ==="

# Copy shared format_values.py from parent directory (if exists)
cp ../format_values.py . 2>/dev/null || true

# Initialize parameters with default values
Run_on_HPC="False"
Table_to_Process="Original"
Number_of_Neighbors=75
Target_Dimension_Number=2
Minimum_Distance_between_Points=0.1
Computational_Metric="euclidean"
Transform_Seed=42
Random_State=0
Batch_Mode="False"
Partition="quick"
Number_of_CPUs=2
Memory_GB=10
Request_Time="00:20:00"

# Print received arguments for debugging
echo "Number of arguments: $#"
echo "Arguments received:"
for arg in "$@"; do
    echo "  $arg"
done

# Parse named arguments dynamically (--param_name=value format)
# Based on Conor's example: single pattern handles all --key=value arguments
for arg in "$@"; do
    case "$arg" in
        --*=*)
            key="${arg%%=*}"      # everything before '='
            value="${arg#*=}"     # everything after '='
            key="${key#--}"       # remove leading '--'
            export "$key=$value"
            ;;
    esac
done

# Debug: Print parsed parameter values
echo "Run_on_HPC: $Run_on_HPC"
echo "Table_to_Process: $Table_to_Process"
echo "Number_of_Neighbors: $Number_of_Neighbors"
echo "Target_Dimension_Number: $Target_Dimension_Number"
echo "Minimum_Distance_between_Points: $Minimum_Distance_between_Points"
echo "Computational_Metric: $Computational_Metric"
echo "Transform_Seed: $Transform_Seed"
echo "Random_State: $Random_State"
echo "Batch_Mode: $Batch_Mode"
echo "Partition: $Partition"
echo "Number_of_CPUs: $Number_of_CPUs"
echo "Memory_GB: $Memory_GB"
echo "Request_Time: $Request_Time"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Run_on_HPC": "$Run_on_HPC",
    "Table_to_Process": "$Table_to_Process",
    "Number_of_Neighbors": $Number_of_Neighbors,
    "Target_Dimension_Number": $Target_Dimension_Number,
    "Minimum_Distance_between_Points": $Minimum_Distance_between_Points,
    "Computational_Metric": "$Computational_Metric",
    "Transform_Seed": $Transform_Seed,
    "Random_State": $Random_State,
    "Batch_Mode": "$Batch_Mode",
    "Partition": "$Partition",
    "Number_of_CPUs": $Number_of_CPUs,
    "Memory_GB": $Memory_GB,
    "Request_Time": "$Request_Time"
}
EOF

echo '{"analysis": {"type": "file", "name": "output.pickle"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Run_on_HPC Batch_Mode --inject-outputs --outputs-config /results/jsons/outputs_config.json

echo "Normalized: /results/jsons/params.json -> /results/jsons/cleaned_params.json"

# Run SPAC template
python -c "from spac.templates.umap_transformation_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json', output_dir='/results')"

echo ""
echo "=== Completed. Outputs in /results/ ==="