#!/usr/bin/env bash
set -euo pipefail

# Append Annotation [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Append Annotation [SPAC] [DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
ANNOTATION_PAIR_LIST="${1:-["Example:Example"]}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Annotation_Pair_List": "$ANNOTATION_PAIR_LIST"
}
EOF

echo '{"dataframe": {"type": "file", "name": "dataframe.csv"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --list-values Annotation_Pair_List --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.append_annotation_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
