#!/usr/bin/env bash
set -euo pipefail

# Spatial Interaction [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Spatial Interaction [SPAC] [DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
ANNOTATION="${1:-}"
SPATIAL_ANALYSIS_METHOD="${2:-Neighborhood Enrichment}"
STRATIFY_BY="${3:-["None"]}"
COORDINATE_TYPE="${4:-None}"
SEED="${5:-None}"
RADIUS="${6:-None}"
K_NEAREST_NEIGHBORS="${7:-6}"
FIGURE_WIDTH="${8:-15}"
FIGURE_HEIGHT="${9:-12}"
FIGURE_DPI="${10:-200}"
FONT_SIZE="${11:-12}"
COLOR_BAR_RANGE="${12:-Automatic}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Annotation": "$ANNOTATION",
    "Spatial_Analysis_Method": "$SPATIAL_ANALYSIS_METHOD",
    "Stratify_By": "$STRATIFY_BY",
    "Coordinate_Type": "$COORDINATE_TYPE",
    "Seed": "$SEED",
    "Radius": "$RADIUS",
    "K_Nearest_Neighbors": "$K_NEAREST_NEIGHBORS",
    "Figure_Width": "$FIGURE_WIDTH",
    "Figure_Height": "$FIGURE_HEIGHT",
    "Figure_DPI": "$FIGURE_DPI",
    "Font_Size": "$FONT_SIZE",
    "Color_Bar_Range": "$COLOR_BAR_RANGE"
}
EOF

echo '{"dataframe": {"type": "file", "name": "dataframe.csv"}, "figures": {"type": "directory", "name": "figures_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --list-values Stratify_By --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.spatial_interaction_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
