#!/usr/bin/env bash
set -euo pipefail

# Spatial Interaction [SPAC] [DMAP]
# Generated by code_ocean_synthesizer.py v9.0 (Single run.sh)
# Named argument parsing: --param_name=value format

echo "=== Spatial Interaction [SPAC] [DMAP] ==="

# Copy shared format_values.py from parent directory (if exists)
cp ../format_values.py . 2>/dev/null || true

# Initialize parameters with default values
Annotation=""
Spatial_Analysis_Method="Neighborhood Enrichment"
Stratify_By="["None"]"
Coordinate_Type="None"
Seed="None"
Radius="None"
K_Nearest_Neighbors=6
Figure_Width=15
Figure_Height=12
Figure_DPI=200
Font_Size=12
Color_Bar_Range="Automatic"

# Print received arguments for debugging
echo "Number of arguments: $#"
echo "Arguments received:"
for arg in "$@"; do
    echo "  $arg"
done

# Parse named arguments dynamically (--param_name=value format)
# Single pattern handles all --key=value arguments
for arg in "$@"; do
    case "$arg" in
        --*=*)
            key="${arg%%=*}"      # everything before '='
            value="${arg#*=}"     # everything after '='
            key="${key#--}"       # remove leading '--'
            export "$key=$value"
            ;;
    esac
done

# Debug: Print parsed parameter values
echo "Annotation: $Annotation"
echo "Spatial_Analysis_Method: $Spatial_Analysis_Method"
echo "Stratify_By: $Stratify_By"
echo "Coordinate_Type: $Coordinate_Type"
echo "Seed: $Seed"
echo "Radius: $Radius"
echo "K_Nearest_Neighbors: $K_Nearest_Neighbors"
echo "Figure_Width: $Figure_Width"
echo "Figure_Height: $Figure_Height"
echo "Figure_DPI: $Figure_DPI"
echo "Font_Size: $Font_Size"
echo "Color_Bar_Range: $Color_Bar_Range"

# Find input data (pickle/pkl/h5ad)
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No pickle/pkl/h5ad file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Annotation": "$Annotation",
    "Spatial_Analysis_Method": "$Spatial_Analysis_Method",
    "Stratify_By": "$Stratify_By",
    "Coordinate_Type": "$Coordinate_Type",
    "Seed": "$Seed",
    "Radius": "$Radius",
    "K_Nearest_Neighbors": $K_Nearest_Neighbors,
    "Figure_Width": $Figure_Width,
    "Figure_Height": $Figure_Height,
    "Figure_DPI": $Figure_DPI,
    "Font_Size": $Font_Size,
    "Color_Bar_Range": "$Color_Bar_Range"
}
EOF

echo '{"dataframe": {"type": "file", "name": "dataframe.csv"}, "figures": {"type": "directory", "name": "figures_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --list-values Stratify_By --inject-outputs --outputs-config /results/jsons/outputs_config.json

echo "Normalized: /results/jsons/params.json -> /results/jsons/cleaned_params.json"

# Run SPAC template
python -c "from spac.templates.spatial_interaction_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json', output_dir='/results')"

echo ""
echo "=== Completed. Outputs in /results/ ==="