#!/usr/bin/env bash
set -euo pipefail

# Visualize Nearest Neighbor [SPAC][DMAP]
# Generated by code_ocean_synthesizer.py v5.0

echo "=== Visualize Nearest Neighbor [SPAC][DMAP] ==="

# Capture App Panel arguments (positional: $1, $2, ...)
ANNOTATION="${1:-}"
IMAGEID="${2:-None}"
PLOT_METHOD="${3:-numeric}"
PLOT_TYPE="${4:-boxen}"
SOURCE_ANCHOR_CELL_LABEL="${5:-}"
TARGET_CELL_LABEL="${6:-All}"
NEAREST_NEIGHBOR_ASSOCIATED_TABLE="${7:-spatial_distance}"
LOG_SCALE="${8:-False}"
FACET_PLOT="${9:-False}"
X_AXIS_LABEL_ROTATION="${10:-0}"
SHARED_X_AXIS_TITLE_="${11:-True}"
X_AXIS_TITLE_FONT_SIZE="${12:-None}"
DEFINED_COLOR_MAPPING="${13:-None}"
FIGURE_WIDTH="${14:-12}"
FIGURE_HEIGHT="${15:-6}"
FIGURE_DPI="${16:-300}"
FONT_SIZE="${17:-12}"

# Find input data
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No input file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Annotation": "$ANNOTATION",
    "ImageID": "$IMAGEID",
    "Plot_Method": "$PLOT_METHOD",
    "Plot_Type": "$PLOT_TYPE",
    "Source_Anchor_Cell_Label": "$SOURCE_ANCHOR_CELL_LABEL",
    "Target_Cell_Label": "$TARGET_CELL_LABEL",
    "Nearest_Neighbor_Associated_Table": "$NEAREST_NEIGHBOR_ASSOCIATED_TABLE",
    "Log_Scale": "$LOG_SCALE",
    "Facet_Plot": "$FACET_PLOT",
    "X_Axis_Label_Rotation": "$X_AXIS_LABEL_ROTATION",
    "Shared_X_Axis_Title_": "$SHARED_X_AXIS_TITLE_",
    "X_Axis_Title_Font_Size": "$X_AXIS_TITLE_FONT_SIZE",
    "Defined_Color_Mapping": "$DEFINED_COLOR_MAPPING",
    "Figure_Width": "$FIGURE_WIDTH",
    "Figure_Height": "$FIGURE_HEIGHT",
    "FIgure_DPI": "$FIGURE_DPI",
    "Font_Size": "$FONT_SIZE"
}
EOF

echo '{"dataframe": {"type": "file", "name": "dataframe.csv"}, "figures": {"type": "directory", "name": "figures_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Log_Scale Facet_Plot Shared_X_Axis_Title_ --inject-outputs --outputs-config /results/jsons/outputs_config.json

# Run SPAC template
python -c "from spac.templates.visualize_nearest_neighbor_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json')"

echo ""
echo "=== Completed. Outputs in /results/ ==="
