#!/usr/bin/env bash
set -euo pipefail

# Visualize Nearest Neighbor [SPAC][DMAP]
# Generated by code_ocean_synthesizer.py v9.0 (Single run.sh)
# Named argument parsing: --param_name=value format

echo "=== Visualize Nearest Neighbor [SPAC][DMAP] ==="

# Copy shared format_values.py from parent directory (if exists)
cp ../format_values.py . 2>/dev/null || true

# Initialize parameters with default values
Annotation=""
ImageID="None"
Plot_Method="numeric"
Plot_Type="boxen"
Source_Anchor_Cell_Label=""
Target_Cell_Label="All"
Nearest_Neighbor_Associated_Table="spatial_distance"
Log_Scale="False"
Facet_Plot="False"
X_Axis_Label_Rotation=0
Shared_X_Axis_Title_="True"
X_Axis_Title_Font_Size="None"
Defined_Color_Mapping="None"
Figure_Width=12
Figure_Height=6
FIgure_DPI=300
Font_Size=12

# Print received arguments for debugging
echo "Number of arguments: $#"
echo "Arguments received:"
for arg in "$@"; do
    echo "  $arg"
done

# Parse named arguments dynamically (--param_name=value format)
# Single pattern handles all --key=value arguments
for arg in "$@"; do
    case "$arg" in
        --*=*)
            key="${arg%%=*}"      # everything before '='
            value="${arg#*=}"     # everything after '='
            key="${key#--}"       # remove leading '--'
            export "$key=$value"
            ;;
    esac
done

# Debug: Print parsed parameter values
echo "Annotation: $Annotation"
echo "ImageID: $ImageID"
echo "Plot_Method: $Plot_Method"
echo "Plot_Type: $Plot_Type"
echo "Source_Anchor_Cell_Label: $Source_Anchor_Cell_Label"
echo "Target_Cell_Label: $Target_Cell_Label"
echo "Nearest_Neighbor_Associated_Table: $Nearest_Neighbor_Associated_Table"
echo "Log_Scale: $Log_Scale"
echo "Facet_Plot: $Facet_Plot"
echo "X_Axis_Label_Rotation: $X_Axis_Label_Rotation"
echo "Shared_X_Axis_Title_: $Shared_X_Axis_Title_"
echo "X_Axis_Title_Font_Size: $X_Axis_Title_Font_Size"
echo "Defined_Color_Mapping: $Defined_Color_Mapping"
echo "Figure_Width: $Figure_Width"
echo "Figure_Height: $Figure_Height"
echo "FIgure_DPI: $FIgure_DPI"
echo "Font_Size: $Font_Size"

# Find input data (pickle/pkl/h5ad)
INPUT=$(find -L ../data -type f \( -name "*.pickle" -o -name "*.pkl" -o -name "*.h5ad" \) 2>/dev/null | head -n 1)
if [ -z "$INPUT" ]; then echo "ERROR: No pickle/pkl/h5ad file found in ../data"; exit 1; fi
echo "Input: $INPUT"

# Create output directories
mkdir -p /results/figures /results/jsons

# Create parameters JSON
cat > /results/jsons/params.json << EOF
{
    "Upstream_Analysis": "$INPUT",
    "Annotation": "$Annotation",
    "ImageID": "$ImageID",
    "Plot_Method": "$Plot_Method",
    "Plot_Type": "$Plot_Type",
    "Source_Anchor_Cell_Label": "$Source_Anchor_Cell_Label",
    "Target_Cell_Label": "$Target_Cell_Label",
    "Nearest_Neighbor_Associated_Table": "$Nearest_Neighbor_Associated_Table",
    "Log_Scale": "$Log_Scale",
    "Facet_Plot": "$Facet_Plot",
    "X_Axis_Label_Rotation": $X_Axis_Label_Rotation,
    "Shared_X_Axis_Title_": "$Shared_X_Axis_Title_",
    "X_Axis_Title_Font_Size": "$X_Axis_Title_Font_Size",
    "Defined_Color_Mapping": "$Defined_Color_Mapping",
    "Figure_Width": $Figure_Width,
    "Figure_Height": $Figure_Height,
    "FIgure_DPI": $FIgure_DPI,
    "Font_Size": $Font_Size
}
EOF

echo '{"dataframe": {"type": "file", "name": "dataframe.csv"}, "figures": {"type": "directory", "name": "figures_dir"}}' > /results/jsons/outputs_config.json

# Normalize parameters
python format_values.py /results/jsons/params.json /results/jsons/cleaned_params.json --bool-values Log_Scale Facet_Plot Shared_X_Axis_Title_ --inject-outputs --outputs-config /results/jsons/outputs_config.json

echo "Normalized: /results/jsons/params.json -> /results/jsons/cleaned_params.json"

# Run SPAC template
python -c "from spac.templates.visualize_nearest_neighbor_template import run_from_json; run_from_json('/results/jsons/cleaned_params.json', output_dir='/results')"

echo ""
echo "=== Completed. Outputs in /results/ ==="